const fullSolutionsData = {
    "운영체제": [
        {n:"Ubuntu",v:"Canonical",l:"GPL",t:"copyleft",u:"ubuntu.com",tags:["Linux","Desktop","Server"],f:["사용자 친화적 인터페이스","5년 LTS 지원","대규모 커뮤니티"],p:["그로윈","대보정보통신","락플레이스","메타비즈","싸이버테크","아이오차드","오케스트로","클럭스","엑셈"]},
        {n:"Debian",v:"Debian Project",l:"DFSG",t:"permissive",u:"debian.org",tags:["Linux","Server","Stable"],f:["높은 안정성","방대한 패키지","엄격한 품질 관리"],p:["대신정보통신","이액티브","태건에스앤아이","와탭랩스"]},
        {n:"CentOS Stream",v:"Red Hat",l:"GPL",t:"copyleft",u:"centos.org",tags:["Linux","Enterprise"],f:["RHEL 업스트림","엔터프라이즈급 안정성","기업 환경 최적화"],p:["그로윈","대보정보통신","리원에이스","샘터정보기술","아온소프트","에스코어","이액티브","클럭스","와탭랩스"]},
        {n:"Rocky Linux",v:"Rocky Enterprise",l:"BSD",t:"permissive",u:"rockylinux.org",tags:["Linux","RHEL"],f:["RHEL 완벽 호환","커뮤니티 주도","무료 엔터프라이즈 OS"],p:["에프에이리눅스","에스코어","엑셈","와탭랩스"]},
        {n:"AlmaLinux",v:"AlmaLinux Foundation",l:"BSD",t:"permissive",u:"almalinux.org",tags:["Linux","RHEL"],f:["CentOS 대체","CloudLinux 후원","장기 지원"],p:["에스코어"]},
        {n:"Fedora",v:"Red Hat",l:"GPL",t:"copyleft",u:"getfedora.org",tags:["Linux","Desktop"],f:["최신 기술 선도","RHEL 테스트베드","6개월 릴리스"],p:["엑셈","와탭랩스"]},
        {n:"openSUSE",v:"SUSE",l:"GPL",t:"copyleft",u:"opensuse.org",tags:["Linux","YaST"],f:["YaST 시스템 관리","Leap/Tumbleweed 선택","유럽 기반"],p:["그로윈","네오클로바","세림티에스지","제이알정보기술","태건에스앤아이","와탭랩스"]},
        {n:"Arch Linux",v:"Arch Community",l:"GPL",t:"copyleft",u:"archlinux.org",tags:["Linux","Rolling"],f:["롤링 릴리스","최소주의 철학","AUR 패키지"],p:[]},
        {n:"Manjaro",v:"Manjaro Community",l:"GPL",t:"copyleft",u:"manjaro.org",tags:["Linux","Desktop"],f:["Arch 기반 사용 편의성","하드웨어 자동 감지","다양한 데스크톱 환경"],p:[]},
        {n:"Linux Mint",v:"Linux Mint Team",l:"GPL",t:"copyleft",u:"linuxmint.com",tags:["Linux","Desktop"],f:["Ubuntu 기반","Cinnamon 데스크톱","초보자 친화적"],p:[]},
        {n:"FreeBSD",v:"FreeBSD Foundation",l:"BSD",t:"permissive",u:"freebsd.org",tags:["BSD","Server"],f:["ZFS 파일시스템","jail 컨테이너","고성능 네트워킹"],p:["리브리오","세림티에스지","엑셈"]},
        {n:"OpenBSD",v:"OpenBSD Project",l:"BSD",t:"permissive",u:"openbsd.org",tags:["BSD","Security"],f:["보안 최우선","코드 감사","OpenSSH 개발"],p:[]},
        {n:"Gooroom",v:"한글과컴퓨터",l:"GPL",t:"copyleft",u:"gooroom.kr",tags:["Linux","국산","보안"],f:["국산 보안 OS","공공기관 최적화","망분리 지원"],p:["이액티브","엑셈","한글과컴퓨터"]},
        {n:"HamoniKR",v:"인베슘",l:"GPL",t:"copyleft",u:"hamonikr.org",tags:["Linux","국산","Desktop"],f:["Ubuntu 기반 국산 OS","한글 완벽 지원","쉬운 사용성"],p:["인베슘","엑셈"]},
        {n:"TmaxOS",v:"티맥스A&C",l:"Commercial",t:"proprietary",u:"tmaxanc.com",tags:["국산","Desktop"],f:["국산 운영체제","MS오피스 호환","독자 기술"],p:["티맥스오에스","엑셈"]},
        {n:"RHEL",v:"Red Hat",l:"GPL",t:"copyleft",u:"redhat.com/rhel",tags:["Linux","Enterprise"],f:["엔터프라이즈 리눅스","장기 지원","기업용 보안"],p:["그로윈","대신정보통신","메타비즈","세림티에스지","에스유소프트","오픈소스컨설팅","지티플러스","한국오픈솔루션"]},
        {n:"Oracle Linux",v:"Oracle",l:"GPL",t:"copyleft",u:"oracle.com/linux",tags:["Linux","Enterprise"],f:["RHEL 호환","Oracle 최적화","Ksplice 지원"],p:["시그마정보통신","시스템어소시에이츠","에티버스","유클릭","이비아이인씨","정우씨에스티","제스프로","클라우드네트웍스","엑셈","와탭랩스"]},
        {n:"Asianux",v:"Asianux",l:"GPL",t:"copyleft",u:"asianux.com",tags:["Linux","아시아"],f:["아시아 맞춤 리눅스","다국어 지원","기업용"],p:["세림티에스지","엑셈"]},
        {n:"SULinux",v:"에스유소프트",l:"GPL",t:"copyleft",u:"sulinux.net",tags:["Linux","국산","Server"],f:["국산 서버 리눅스","보안 강화","기술지원"],p:["세림티에스지","에스유소프트","엑셈"]},
        {n:"Scientific Linux",v:"Fermilab/CERN",l:"GPL",t:"copyleft",u:"scientificlinux.org",tags:["Linux","과학"],f:["과학 연구용","RHEL 호환","안정성"],p:["에스유소프트","케이엘정보통신","엑셈"]}
    ],
    "데이터베이스": [
        {n:"PostgreSQL",v:"PostgreSQL Global",l:"PostgreSQL",t:"permissive",u:"postgresql.org",tags:["RDBMS","SQL","ACID"],f:["ACID 완벽 지원","복잡한 쿼리 최적화","JSON/XML 지원"],p:["그로윈","네오클로바","리눅스데이타시스템","범일정보","싸이웰시스템","에스코어","웨이버스","헤르메시스"]},
        {n:"MySQL",v:"Oracle",l:"GPL v2",t:"copyleft",u:"mysql.com",tags:["RDBMS","SQL","Web"],f:["웹 애플리케이션 표준","InnoDB 스토리지 엔진","복제 및 클러스터링"],p:["유클릭","굿어스데이타","락플레이스","시스원","에스코어"]},
        {n:"MariaDB",v:"MariaDB Foundation",l:"GPL v2",t:"copyleft",u:"mariadb.org",tags:["RDBMS","MySQL"],f:["MySQL 완벽 호환","성능 개선","새로운 스토리지 엔진"],p:["그로윈","대보정보통신","리눅스데이타시스템","범일정보","싸이웰시스템","에스엠티정보기술","오케스트로","젠탑테크놀로지","엑셈"]},
        {n:"MongoDB",v:"MongoDB Inc",l:"SSPL",t:"copyleft",u:"mongodb.com",tags:["NoSQL","Document"],f:["유연한 스키마","수평 확장","JSON 기반 문서"],p:["그로윈","락플레이스","오케스트로","코오롱베니트","헤르메시스","에스코어","엑셈","와탭랩스"]},
        {n:"Redis",v:"Redis Ltd",l:"BSD",t:"permissive",u:"redis.io",tags:["NoSQL","Cache","Memory"],f:["인메모리 속도","다양한 자료구조","Pub/Sub 메시징"],p:["그로윈","두타아이티","락플레이스","아온소프트","에스코어","엑셈","티맥스소프트","와탭랩스"]},
        {n:"Cassandra",v:"Apache",l:"Apache 2.0",t:"permissive",u:"cassandra.apache.org",tags:["NoSQL","Distributed"],f:["대규모 분산 처리","고가용성","선형 확장성"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"Percona Server",v:"Percona",l:"GPL v2",t:"copyleft",u:"percona.com",tags:["RDBMS","MySQL"],f:["MySQL 호환","성능 개선","엔터프라이즈 기능"],p:["네오클로바","락플레이스","아온소프트"]},
        {n:"CouchDB",v:"Apache",l:"Apache 2.0",t:"permissive",u:"couchdb.apache.org",tags:["NoSQL","Document"],f:["HTTP REST API","멀티 마스터 복제","오프라인 동기화"],p:[]},
        {n:"CUBRID",v:"큐브리드",l:"GPL v2",t:"copyleft",u:"cubrid.com",tags:["RDBMS","국산"],f:["웹 환경 최적화","HA 기능","한글 완벽 지원"],p:["범일정보","쓰리에이치에스","엑소텍","큐브리드","엑셈","와탭랩스"]},
        {n:"Tibero",v:"티맥스소프트",l:"Commercial",t:"proprietary",u:"tmaxsoft.com",tags:["RDBMS","국산"],f:["Oracle 호환","고성능 처리","국내 기술 지원"],p:["티맥스소프트","티맥스데이터"]},
        {n:"InfluxDB",v:"InfluxData",l:"MIT",t:"permissive",u:"influxdata.com",tags:["NoSQL","TimeSeries"],f:["시계열 데이터 최적화","SQL 유사 쿼리","고속 데이터 수집"],p:["락플레이스"]},
        {n:"Neo4j",v:"Neo4j Inc",l:"GPL v3",t:"copyleft",u:"neo4j.com",tags:["NoSQL","Graph"],f:["그래프 데이터베이스","Cypher 쿼리 언어","관계 분석 최적화"],p:["비트나인"]},
        {n:"AgensGraph",v:"비트나인",l:"Apache 2.0",t:"permissive",u:"bitnine.net",tags:["NoSQL","Graph","국산"],f:["그래프 DB","PostgreSQL 기반","하이브리드 쿼리"],p:["비트나인","엑셈"]},
        {n:"EDB Postgres",v:"EDB",l:"PostgreSQL",t:"permissive",u:"enterprisedb.com",tags:["RDBMS","PostgreSQL"],f:["Oracle 호환","엔터프라이즈급","고가용성"],p:["락플레이스","이레IDS","에이치씨인포","에스코어","엑셈"]},
        {n:"Elasticsearch",v:"Elastic",l:"SSPL",t:"copyleft",u:"elastic.co",tags:["NoSQL","Search"],f:["전문 검색 엔진","분산 아키텍처","실시간 분석"],p:["누리꿈소프트","엘라스틱서치코리아","에스코어"]},
        {n:"Memcached",v:"Memcached",l:"BSD",t:"permissive",u:"memcached.org",tags:["Cache","Memory"],f:["단순하고 빠름","분산 캐싱","낮은 메모리 사용"],p:[]},
        {n:"RocksDB",v:"Meta",l:"Apache 2.0",t:"permissive",u:"rocksdb.org",tags:["NoSQL","Embedded"],f:["임베디드 KV 스토어","SSD 최적화","압축 지원"],p:[]},
        {n:"SQLite",v:"SQLite",l:"Public Domain",t:"permissive",u:"sqlite.org",tags:["RDBMS","Embedded"],f:["서버리스","단일 파일 DB","제로 설정"],p:[]},
        {n:"ArangoDB",v:"ArangoDB",l:"Apache 2.0",t:"permissive",u:"arangodb.com",tags:["NoSQL","Multi-model"],f:["멀티모델 지원","AQL 쿼리 언어","그래프+문서+KV"],p:[]},
        {n:"Couchbase",v:"Couchbase",l:"Apache 2.0",t:"permissive",u:"couchbase.com",tags:["NoSQL","Document"],f:["N1QL 쿼리","메모리 우선 아키텍처","모바일 동기화"],p:[]},
        {n:"ScyllaDB",v:"ScyllaDB",l:"AGPL",t:"copyleft",u:"scylladb.com",tags:["NoSQL","Cassandra-compatible"],f:["Cassandra 호환","C++ 성능","낮은 레이턴시"],p:[]},
        {n:"Altibase",v:"알티베이스",l:"AGPL",t:"copyleft",u:"altibase.com",tags:["RDBMS","국산","In-memory"],f:["하이브리드 DBMS","인메모리 성능","이중화 지원"],p:["알티베이스","엑셈","와탭랩스"]},
        {n:"Goldilocks",v:"선재소프트",l:"Commercial",t:"proprietary",u:"sunjesoft.com",tags:["RDBMS","국산","In-memory"],f:["인메모리 DB","실시간 처리","고가용성"],p:["선재소프트"]},
        {n:"Kairos",v:"리얼타임테크",l:"Commercial",t:"proprietary",u:"realtimetech.co.kr",tags:["TimeSeries","국산"],f:["시계열 DB","IoT 최적화","고속 처리"],p:["리얼타임테크"]},
        {n:"Apache Solr",v:"Apache",l:"Apache 2.0",t:"permissive",u:"solr.apache.org",tags:["Search","NoSQL"],f:["전문 검색 엔진","분산 검색","패싯 검색"],p:["한국루씬커뮤니티"]},
        {n:"Milvus",v:"Zilliz",l:"Apache 2.0",t:"permissive",u:"milvus.io",tags:["VectorDB","AI"],f:["벡터 데이터베이스","AI/ML 최적화","유사도 검색"],p:["에스코어"]},
        {n:"Weaviate",v:"Weaviate",l:"BSD",t:"permissive",u:"weaviate.io",tags:["VectorDB","AI"],f:["벡터 검색 엔진","GraphQL API","시맨틱 검색"],p:["에스코어"]},
        {n:"Apache Ignite",v:"Apache",l:"Apache 2.0",t:"permissive",u:"ignite.apache.org",tags:["In-memory","Distributed"],f:["인메모리 컴퓨팅","분산 캐시","SQL 지원"],p:["에스코어"]},
        {n:"Apache HBase",v:"Apache",l:"Apache 2.0",t:"permissive",u:"hbase.apache.org",tags:["NoSQL","BigData"],f:["분산 컬럼 스토어","Hadoop 기반","대용량 처리"],p:["BIC데이터"]},
        {n:"Apache AGE",v:"Apache",l:"Apache 2.0",t:"permissive",u:"age.apache.org",tags:["Graph","PostgreSQL"],f:["그래프 확장","PostgreSQL 기반","Cypher 지원"],p:["비트나인"]},
        {n:"Splunk",v:"Splunk",l:"Commercial",t:"proprietary",u:"splunk.com",tags:["분석","로그"],f:["로그 분석","실시간 모니터링","보안 분석"],p:["리눅스데이타시스템","오에스에스랩"]},
        {n:"Hazelcast",v:"Hazelcast",l:"Apache 2.0",t:"permissive",u:"hazelcast.com",tags:["In-memory","Cache"],f:["분산 캐시","인메모리 그리드","스트리밍"],p:[]},
        {n:"ARCUS",v:"네이버",l:"Apache 2.0",t:"permissive",u:"github.com/naver/arcus",tags:["Cache","국산"],f:["분산 캐시","Memcached 호환","네이버 개발"],p:["잼투인"]},
        {n:"eXperDB",v:"엔터프라이즈DB",l:"Commercial",t:"proprietary",u:"experdb.com",tags:["RDBMS","PostgreSQL"],f:["PostgreSQL 기반","국산 기술지원","엔터프라이즈급"],p:["인젠트","데이터숲","신세계아이앤씨","인비전아이티"]},
        {n:"Flamingo",v:"엑셈",l:"Apache 2.0",t:"permissive",u:"github.com/exem-inc/flamingo",tags:["BigData","Hadoop"],f:["빅데이터 관리","Hadoop 통합","GUI 제공"],p:["대보정보통신","엑셈"]},
        {n:"Tajo",v:"Apache",l:"Apache 2.0",t:"permissive",u:"tajo.apache.org",tags:["BigData","SQL"],f:["분산 데이터 웨어하우스","SQL on Hadoop","한국 개발"],p:["대보정보통신"]}
    ],
    "WAS/웹서버": [
        {n:"Apache HTTP",v:"Apache",l:"Apache 2.0",t:"permissive",u:"httpd.apache.org",tags:["웹서버","HTTP"],f:["모듈 기반 아키텍처","안정적인 성능","광범위한 호환성"],p:["그로윈","대신정보통신","리브리오","비온시이노베이터","싸이웰시스템","에스유소프트","오케스트로","인투사이트","티맥스소프트"]},
        {n:"Nginx",v:"Nginx Inc",l:"BSD",t:"permissive",u:"nginx.org",tags:["웹서버","Proxy"],f:["비동기 이벤트 기반","리버스 프록시","낮은 메모리 사용"],p:["그로윈","락플레이스","리원에이스","아이오차드","에스유소프트","젠탑테크놀로지","엑셈"]},
        {n:"Apache Tomcat",v:"Apache",l:"Apache 2.0",t:"permissive",u:"tomcat.apache.org",tags:["WAS","Java"],f:["서블릿 컨테이너","JSP 엔진","경량 WAS"],p:["그로윈","대신정보통신","리드어스","범일정보","싸이버테크","에스엠티정보기술","오케스트로","윤커뮤니케이션즈","지티플러스","휴먼정보"]},
        {n:"WildFly",v:"Red Hat",l:"LGPL",t:"copyleft",u:"wildfly.org",tags:["WAS","JBoss"],f:["Java EE 완전 지원","마이크로서비스 대응","클러스터링 기능"],p:["그로윈","네오클로바","락플레이스","리원에이스","아온소프트","에스유소프트","오케스트로","엑소텍","티맥스소프트","와탭랩스"]},
        {n:"Jetty",v:"Eclipse",l:"Apache 2.0",t:"permissive",u:"eclipse.org/jetty",tags:["WAS","Java"],f:["임베디드 사용 가능","비동기 HTTP","경량 구조"],p:["락플레이스"]},
        {n:"JEUS",v:"티맥스소프트",l:"Commercial",t:"proprietary",u:"tmaxsoft.com",tags:["WAS","국산"],f:["국산 WAS","WebLogic 호환","엔터프라이즈 기능"],p:["티맥스소프트"]},
        {n:"WebtoB",v:"티맥스소프트",l:"Commercial",t:"proprietary",u:"tmaxsoft.com",tags:["웹서버","국산"],f:["국산 웹서버","고성능 처리","WAS 연동 최적화"],p:["티맥스소프트"]},
        {n:"HAProxy",v:"HAProxy Tech",l:"GPL v2",t:"copyleft",u:"haproxy.org",tags:["LoadBalancer","Proxy"],f:["고가용성 로드밸런서","TCP/HTTP 프록시","헬스체크 기능"],p:["래빗소프트","세림티에스지","에스코어"]},
        {n:"Envoy",v:"CNCF",l:"Apache 2.0",t:"permissive",u:"envoyproxy.io",tags:["Proxy","ServiceMesh"],f:["서비스 메시 프록시","동적 설정","관찰성 내장"],p:["락플레이스","오픈소스컨설팅","에스코어"]},
        {n:"Traefik",v:"Traefik Labs",l:"MIT",t:"permissive",u:"traefik.io",tags:["Proxy","LoadBalancer"],f:["자동 서비스 발견","Let's Encrypt 통합","동적 리로딩"],p:["락플레이스"]},
        {n:"Caddy",v:"Caddy",l:"Apache 2.0",t:"permissive",u:"caddyserver.com",tags:["웹서버","HTTPS"],f:["자동 HTTPS","간편한 설정","HTTP/3 지원"],p:[]},
        {n:"Lighttpd",v:"Lighttpd",l:"BSD",t:"permissive",u:"lighttpd.net",tags:["웹서버","경량"],f:["경량 웹서버","낮은 리소스 사용","FastCGI 지원"],p:[]},
        {n:"GlassFish",v:"Eclipse",l:"EPL",t:"permissive",u:"glassfish.org",tags:["WAS","Java EE"],f:["Java EE 레퍼런스","관리 콘솔","클러스터링"],p:["락플레이스"]},
        {n:"Undertow",v:"Red Hat",l:"Apache 2.0",t:"permissive",u:"undertow.io",tags:["웹서버","Java"],f:["유연한 아키텍처","블로킹/논블로킹","임베드 가능"],p:["락플레이스"]},
        {n:"JBoss EAP",v:"Red Hat",l:"LGPL",t:"copyleft",u:"redhat.com/jboss",tags:["WAS","Enterprise"],f:["엔터프라이즈 WAS","Java EE 지원","클러스터링"],p:["그로윈","리눅스데이타시스템","세림티에스지","에스코어","윤커뮤니케이션즈","레드햇","와탭랩스"]},
        {n:"JBoss Web Server",v:"Red Hat",l:"LGPL",t:"copyleft",u:"redhat.com",tags:["웹서버","Tomcat"],f:["엔터프라이즈 웹서버","Tomcat 기반","기술지원"],p:["그로윈","리원에이스","싸이웰시스템","에티버스","윤커뮤니케이션즈","코오롱베니트","엑셈"]},
        {n:"Resin",v:"Caucho",l:"GPL",t:"copyleft",u:"caucho.com",tags:["WAS","Java"],f:["고성능 WAS","임베디드 기능","빠른 시작"],p:["세림티에스지","엑셈"]},
        {n:"uWSGI",v:"uWSGI",l:"GPL v2",t:"copyleft",u:"uwsgi-docs.readthedocs.io",tags:["WAS","Python"],f:["Python WSGI","다중 프로토콜","플러그인 아키텍처"],p:["아이오차드","와탭랩스"]},
        {n:"ProFTPD",v:"ProFTPD",l:"GPL",t:"copyleft",u:"proftpd.org",tags:["FTP","서버"],f:["FTP 서버","보안 기능","모듈형 구조"],p:["에스유소프트"]}
    ],
    "클라우드/컨테이너": [
        {n:"Kubernetes",v:"CNCF",l:"Apache 2.0",t:"permissive",u:"kubernetes.io",tags:["Container","K8s"],f:["컨테이너 오케스트레이션","자동 스케일링","자가 치유"],p:["네오클로바","락플레이스","아이오차드","오에스씨코리아","오픈소스컨설팅","엑셈"]},
        {n:"Docker",v:"Docker Inc",l:"Apache 2.0",t:"permissive",u:"docker.com",tags:["Container","DevOps"],f:["컨테이너 플랫폼","이미지 빌드","레지스트리 제공"],p:["그로윈","누리꿈소프트","대보정보통신","덕풍정보기술","락플레이스","리원에이스","아온소프트","아이오차드","에스코어","오케스트로","와탭랩스"]},
        {n:"OpenStack",v:"OpenInfra",l:"Apache 2.0",t:"permissive",u:"openstack.org",tags:["Cloud","IaaS"],f:["프라이빗 클라우드","모듈형 아키텍처","멀티테넌시"],p:["그로윈","대보정보통신","리원에이스","싸이웰시스템","아이오차드","오픈소스컨설팅"]},
        {n:"CloudStack",v:"Apache",l:"Apache 2.0",t:"permissive",u:"cloudstack.apache.org",tags:["Cloud","IaaS"],f:["IaaS 플랫폼","멀티 하이퍼바이저","자동 관리"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"Rancher",v:"SUSE",l:"Apache 2.0",t:"permissive",u:"rancher.com",tags:["K8s","Management"],f:["K8s 관리 플랫폼","멀티 클러스터","통합 보안"],p:["오에스씨코리아","에스코어"]},
        {n:"K3s",v:"SUSE",l:"Apache 2.0",t:"permissive",u:"k3s.io",tags:["K8s","Edge"],f:["경량 K8s","엣지 최적화","단일 바이너리"],p:["수세코리아","락플레이스"]},
        {n:"Helm",v:"CNCF",l:"Apache 2.0",t:"permissive",u:"helm.sh",tags:["K8s","Package"],f:["K8s 패키지 매니저","차트 저장소","버전 관리"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"Istio",v:"CNCF",l:"Apache 2.0",t:"permissive",u:"istio.io",tags:["ServiceMesh","K8s"],f:["서비스 메시","트래픽 관리","보안 통신"],p:["락플레이스","오픈소스컨설팅","에스코어"]},
        {n:"Prometheus",v:"CNCF",l:"Apache 2.0",t:"permissive",u:"prometheus.io",tags:["Monitoring","Metrics"],f:["메트릭 수집","시계열 DB","알림 시스템"],p:["에스코어","아이오차드"]},
        {n:"Grafana",v:"Grafana Labs",l:"AGPL",t:"copyleft",u:"grafana.com",tags:["Visualization","Dashboard"],f:["데이터 시각화","대시보드 구성","다중 데이터소스"],p:["에스코어"]},
        {n:"Portainer",v:"Portainer",l:"Zlib",t:"permissive",u:"portainer.io",tags:["Docker","Management"],f:["컨테이너 관리 UI","간편한 배포","RBAC 지원"],p:["락플레이스"]},
        {n:"containerd",v:"CNCF",l:"Apache 2.0",t:"permissive",u:"containerd.io",tags:["Container","Runtime"],f:["컨테이너 런타임","OCI 표준","경량 데몬"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"Podman",v:"Red Hat",l:"Apache 2.0",t:"permissive",u:"podman.io",tags:["Container","Daemonless"],f:["데몬리스 컨테이너","루트리스 실행","Docker 호환"],p:["락플레이스"]},
        {n:"LXC/LXD",v:"Linux Containers",l:"LGPL",t:"copyleft",u:"linuxcontainers.org",tags:["Container","System"],f:["시스템 컨테이너","VM 유사 경험","이미지 관리"],p:[]},
        {n:"Nomad",v:"HashiCorp",l:"MPL",t:"copyleft",u:"nomadproject.io",tags:["Orchestration","Scheduler"],f:["워크로드 오케스트레이션","멀티 플랫폼","간편한 설정"],p:["락플레이스"]},
        {n:"OpenShift",v:"Red Hat",l:"Apache 2.0",t:"permissive",u:"openshift.com",tags:["K8s","PaaS"],f:["엔터프라이즈 K8s","개발자 도구","CI/CD 통합"],p:["네오클로바","싸이웰시스템","한국레드햇","엑셈"]},
        {n:"Argo CD",v:"CNCF",l:"Apache 2.0",t:"permissive",u:"argoproj.github.io",tags:["GitOps","CD"],f:["GitOps CD","선언적 배포","자동 동기화"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"Flux",v:"CNCF",l:"Apache 2.0",t:"permissive",u:"fluxcd.io",tags:["GitOps","CD"],f:["GitOps 툴킷","자동 배포","Helm 통합"],p:["락플레이스"]},
        {n:"Accordion",v:"맨텍",l:"Apache 2.0",t:"permissive",u:"accordions.co.kr",tags:["K8s","국산","PaaS"],f:["국산 K8s 플랫폼","하이브리드 클라우드","엔터프라이즈급"],p:["퍼즐시스템즈","마이웨어","비전테크","아이웍스","네오클로바","엑셈","와탭랩스"]},
        {n:"ProLinux",v:"티맥스에이앤씨",l:"Commercial",t:"proprietary",u:"tmaxanc.com",tags:["Linux","국산","Enterprise"],f:["국산 엔터프라이즈 리눅스","기술지원","보안 패치"],p:["티맥스에이앤씨"]},
        {n:"Kubecost",v:"Kubecost",l:"Apache 2.0",t:"permissive",u:"kubecost.com",tags:["K8s","비용관리"],f:["K8s 비용 모니터링","리소스 최적화","예산 관리"],p:["오에스씨코리아"]},
        {n:"Tigera",v:"Tigera",l:"Apache 2.0",t:"permissive",u:"tigera.io",tags:["K8s","네트워크"],f:["K8s 네트워크 보안","Calico 기반","정책 관리"],p:["오에스씨코리아"]},
        {n:"PaaS-TA",v:"정보통신산업진흥원",l:"Apache 2.0",t:"permissive",u:"paas-ta.kr",tags:["PaaS","국산","클라우드"],f:["국산 PaaS","Cloud Foundry 기반","공공 클라우드"],p:["인프라닉스","크로센트","클라우드포유","나무기술","스마일서브","디딤365"]},
        {n:"Cocktail Cloud",v:"아콘소프트",l:"Commercial",t:"proprietary",u:"cocktailcloud.io",tags:["K8s","국산","관리"],f:["K8s 통합관리","멀티 클라우드","DevOps"],p:["아콘소프트","사이람","엘에스글로벌","지에스아이티엠","인피노브","스마트씨앤아이"]},
        {n:"SpaceONE",v:"메가존클라우드",l:"Apache 2.0",t:"permissive",u:"spaceone.org",tags:["클라우드","관리","국산"],f:["멀티 클라우드 관리","자동화","비용 최적화"],p:["메가존클라우드"]},
        {n:"Cloudit",v:"이노그리드",l:"Commercial",t:"proprietary",u:"innogrid.com",tags:["클라우드","국산"],f:["클라우드 관리","가상화","자동화"],p:["이노그리드"]},
        {n:"Playce Kube",v:"오픈소스컨설팅",l:"Commercial",t:"proprietary",u:"osci.kr",tags:["K8s","국산"],f:["K8s 배포관리","엔터프라이즈급","자동화"],p:["오픈소스컨설팅"]},
        {n:"Playce RoRo",v:"오픈소스컨설팅",l:"Commercial",t:"proprietary",u:"osci.kr",tags:["마이그레이션","클라우드"],f:["클라우드 마이그레이션","자동 분석","리팩토링"],p:["오픈소스컨설팅"]}
    ],
    "빅데이터": [
        {n:"Hadoop",v:"Apache",l:"Apache 2.0",t:"permissive",u:"hadoop.apache.org",tags:["BigData","HDFS"],f:["분산 파일 시스템","맵리듀스 처리","대용량 데이터"],p:["누리꿈소프트","엑소텍"]},
        {n:"Spark",v:"Apache",l:"Apache 2.0",t:"permissive",u:"spark.apache.org",tags:["BigData","Analytics"],f:["인메모리 처리","통합 분석 엔진","배치/스트림"],p:["누리꿈소프트","대보정보통신","에스코어","엑셈"]},
        {n:"Flink",v:"Apache",l:"Apache 2.0",t:"permissive",u:"flink.apache.org",tags:["BigData","Stream"],f:["실시간 스트림 처리","상태 관리","정확히 한번 보장"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"Kafka",v:"Apache",l:"Apache 2.0",t:"permissive",u:"kafka.apache.org",tags:["Messaging","Stream"],f:["분산 스트리밍","높은 처리량","내구성 보장"],p:["에스코어"]},
        {n:"Confluent",v:"Confluent",l:"Confluent Community",t:"copyleft",u:"confluent.io",tags:["Messaging","Kafka"],f:["Kafka 엔터프라이즈","스트리밍 플랫폼","Schema Registry"],p:["에스코어"]},
        {n:"MapReduce",v:"Apache",l:"Apache 2.0",t:"permissive",u:"hadoop.apache.org",tags:["BigData","처리"],f:["분산 처리 모델","대용량 데이터","배치 처리"],p:["대보정보통신","엑셈"]},
        {n:"Apache Zookeeper",v:"Apache",l:"Apache 2.0",t:"permissive",u:"zookeeper.apache.org",tags:["BigData","조정"],f:["분산 조정 서비스","설정 관리","네이밍 서비스"],p:["엑셈"]},
        {n:"Airflow",v:"Apache",l:"Apache 2.0",t:"permissive",u:"airflow.apache.org",tags:["Workflow","ETL"],f:["워크플로우 관리","DAG 기반","스케줄링"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"NiFi",v:"Apache",l:"Apache 2.0",t:"permissive",u:"nifi.apache.org",tags:["DataFlow","ETL"],f:["데이터 플로우 자동화","웹 UI","프로세서 체인"],p:["락플레이스","클라우데라"]},
        {n:"Hive",v:"Apache",l:"Apache 2.0",t:"permissive",u:"hive.apache.org",tags:["BigData","SQL"],f:["SQL 쿼리 인터페이스","Hadoop 통합","데이터 웨어하우스"],p:["락플레이스","오픈소스컨설팅","클라우데라","케이티넥스알","오에스씨코리아","엑셈"]},
        {n:"Presto",v:"Linux Foundation",l:"Apache 2.0",t:"permissive",u:"prestodb.io",tags:["BigData","Query"],f:["분산 SQL 엔진","다중 데이터소스","대화형 분석"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"Trino",v:"Trino",l:"Apache 2.0",t:"permissive",u:"trino.io",tags:["BigData","Query"],f:["고속 SQL 쿼리","연합 쿼리","MPP 아키텍처"],p:["락플레이스"]},
        {n:"Storm",v:"Apache",l:"Apache 2.0",t:"permissive",u:"storm.apache.org",tags:["BigData","Stream"],f:["실시간 계산","확장 가능","내결함성"],p:["락플레이스","핀스정보기술"]},
        {n:"Samza",v:"Apache",l:"Apache 2.0",t:"permissive",u:"samza.apache.org",tags:["BigData","Stream"],f:["스트림 처리 프레임워크","Kafka 통합","상태 저장"],p:[]},
        {n:"Druid",v:"Apache",l:"Apache 2.0",t:"permissive",u:"druid.apache.org",tags:["BigData","Analytics"],f:["실시간 분석 DB","OLAP 쿼리","빠른 집계"],p:["오에스씨코리아"]},
        {n:"Apache Hive",v:"Apache",l:"Apache 2.0",t:"permissive",u:"hive.apache.org",tags:["BigData","SQL"],f:["SQL 쿼리 인터페이스","Hadoop 통합","데이터 웨어하우스"],p:["케이티넥스알","오에스씨코리아","엑셈"]},
        {n:"Pinot",v:"Apache",l:"Apache 2.0",t:"permissive",u:"pinot.apache.org",tags:["BigData","OLAP"],f:["실시간 OLAP","낮은 레이턴시","대규모 확장"],p:[]},
        {n:"Kylin",v:"Apache",l:"Apache 2.0",t:"permissive",u:"kylin.apache.org",tags:["BigData","OLAP"],f:["OLAP 큐브 엔진","사전 집계","초고속 쿼리"],p:[]},
        {n:"Beam",v:"Apache",l:"Apache 2.0",t:"permissive",u:"beam.apache.org",tags:["BigData","Pipeline"],f:["통합 프로그래밍 모델","배치/스트림","다중 실행 엔진"],p:[]},
        {n:"DataStreams",v:"그루터",l:"Apache 2.0",t:"permissive",u:"gruter.com",tags:["BigData","국산","Platform"],f:["빅데이터 플랫폼","실시간 분석","국산 기술지원"],p:["그루터"]}
    ],
    "AI/머신러닝": [
        {n:"TensorFlow",v:"Google",l:"Apache 2.0",t:"permissive",u:"tensorflow.org",tags:["ML","DeepLearning"],f:["딥러닝 프레임워크","분산 학습","프로덕션 배포"],p:["누리꿈소프트","대보정보통신","엑소텍","오케스트로"]},
        {n:"PyTorch",v:"Meta",l:"BSD",t:"permissive",u:"pytorch.org",tags:["ML","DeepLearning"],f:["동적 계산 그래프","연구 친화적","GPU 가속"],p:["락플레이스","솔트룩스","마인즈랩","업스테이지"]},
        {n:"Scikit-learn",v:"Community",l:"BSD",t:"permissive",u:"scikit-learn.org",tags:["ML","Python"],f:["머신러닝 라이브러리","다양한 알고리즘","간편한 API"],p:["락플레이스"]},
        {n:"Keras",v:"Google",l:"Apache 2.0",t:"permissive",u:"keras.io",tags:["ML","API"],f:["고수준 API","빠른 프로토타이핑","멀티 백엔드"],p:["락플레이스"]},
        {n:"Hugging Face",v:"Hugging Face",l:"Apache 2.0",t:"permissive",u:"huggingface.co",tags:["ML","NLP"],f:["사전학습 모델","Transformers","모델 허브"],p:["업스테이지","솔트룩스"]},
        {n:"MLflow",v:"Databricks",l:"Apache 2.0",t:"permissive",u:"mlflow.org",tags:["MLOps","Tracking"],f:["실험 추적","모델 관리","배포 자동화"],p:["락플레이스","데이터브릭스"]},
        {n:"Kubeflow",v:"Google",l:"Apache 2.0",t:"permissive",u:"kubeflow.org",tags:["MLOps","K8s"],f:["ML on K8s","파이프라인","분산 학습"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"Ray",v:"Anyscale",l:"Apache 2.0",t:"permissive",u:"ray.io",tags:["ML","Distributed"],f:["분산 컴퓨팅","강화학습","확장 가능"],p:[]},
        {n:"XGBoost",v:"DMLC",l:"Apache 2.0",t:"permissive",u:"xgboost.ai",tags:["ML","GradientBoosting"],f:["그래디언트 부스팅","고성능","병렬 처리"],p:[]},
        {n:"LightGBM",v:"Microsoft",l:"MIT",t:"permissive",u:"lightgbm.readthedocs.io",tags:["ML","GradientBoosting"],f:["빠른 학습 속도","메모리 효율","대규모 데이터"],p:[]},
        {n:"OpenCV",v:"OpenCV",l:"Apache 2.0",t:"permissive",u:"opencv.org",tags:["CV","Vision"],f:["컴퓨터 비전","이미지 처리","실시간 처리"],p:["락플레이스"]},
        {n:"ONNX",v:"Linux Foundation",l:"Apache 2.0",t:"permissive",u:"onnx.ai",tags:["ML","Interoperability"],f:["모델 상호 운용성","표준 포맷","크로스 플랫폼"],p:[]},
        {n:"MXNet",v:"Apache",l:"Apache 2.0",t:"permissive",u:"mxnet.apache.org",tags:["ML","DeepLearning"],f:["효율적인 메모리","다중 언어 API","분산 학습"],p:[]},
        {n:"Caffe",v:"BVLC",l:"BSD",t:"permissive",u:"caffe.berkeleyvision.org",tags:["ML","DeepLearning"],f:["CNN 특화","빠른 추론","모듈식 구조"],p:[]},
        {n:"FastAI",v:"fast.ai",l:"Apache 2.0",t:"permissive",u:"fast.ai",tags:["ML","Education"],f:["쉬운 학습","최신 기법","교육 중심"],p:[]},
        {n:"Ludwig",v:"Uber",l:"Apache 2.0",t:"permissive",u:"ludwig.ai",tags:["ML","AutoML"],f:["코드 없는 ML","선언적 설정","AutoML"],p:[]},
        {n:"KoNLPy",v:"커뮤니티",l:"GPL v3",t:"copyleft",u:"konlpy.org",tags:["NLP","국산","한국어"],f:["한국어 NLP","형태소 분석","다양한 분석기"],p:["솔트룩스"]},
        {n:"Pororo",v:"카카오브레인",l:"Apache 2.0",t:"permissive",u:"github.com/kakaobrain/pororo",tags:["NLP","국산","Multi-task"],f:["한국어 NLP","멀티태스크","사전학습 모델"],p:["카카오브레인"]}
    ],
    "개발도구": [
        {n:"Git",v:"Linus Torvalds",l:"GPL v2",t:"copyleft",u:"git-scm.com",tags:["VCS","DevOps"],f:["분산 버전 관리","브랜치 관리","속도 최적화"],p:["락플레이스","오픈소스컨설팅","아온소프트","오케스트로"]},
        {n:"GitLab",v:"GitLab",l:"MIT",t:"permissive",u:"gitlab.com",tags:["DevOps","CI/CD"],f:["DevOps 플랫폼","통합 CI/CD","프로젝트 관리"],p:["아이오차드","티맥스소프트"]},
        {n:"Jenkins",v:"Jenkins Project",l:"MIT",t:"permissive",u:"jenkins.io",tags:["CI/CD","Automation"],f:["자동화 서버","플러그인 생태계","파이프라인"],p:["아온소프트","아이오차드","오케스트로","티맥스소프트"]},
        {n:"VS Code",v:"Microsoft",l:"MIT",t:"permissive",u:"code.visualstudio.com",tags:["IDE","Editor"],f:["경량 에디터","확장 기능","통합 터미널"],p:[]},
        {n:"Eclipse",v:"Eclipse Foundation",l:"EPL",t:"permissive",u:"eclipse.org",tags:["IDE","Java"],f:["Java 개발 IDE","플러그인 아키텍처","리팩토링 도구"],p:["락플레이스"]},
        {n:"IntelliJ IDEA CE",v:"JetBrains",l:"Apache 2.0",t:"permissive",u:"jetbrains.com/idea",tags:["IDE","Java"],f:["지능형 코딩 지원","강력한 리팩토링","프레임워크 통합"],p:[]},
        {n:"SonarQube",v:"SonarSource",l:"LGPL",t:"copyleft",u:"sonarqube.org",tags:["Quality","Analysis"],f:["코드 품질 분석","보안 취약점","기술 부채 관리"],p:["락플레이스","오픈소스컨설팅","맨텍","스패로우"]},
        {n:"Nexus",v:"Sonatype",l:"EPL",t:"permissive",u:"sonatype.com",tags:["Repository","Maven"],f:["아티팩트 저장소","프록시 캐싱","보안 스캔"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"Maven",v:"Apache",l:"Apache 2.0",t:"permissive",u:"maven.apache.org",tags:["Build","Java"],f:["프로젝트 관리","의존성 관리","빌드 자동화"],p:["락플레이스"]},
        {n:"Gradle",v:"Gradle Inc",l:"Apache 2.0",t:"permissive",u:"gradle.org",tags:["Build","Java"],f:["유연한 빌드","증분 빌드","멀티 프로젝트"],p:["락플레이스"]},
        {n:"Vim",v:"Bram Moolenaar",l:"Vim",t:"permissive",u:"vim.org",tags:["Editor","Terminal"],f:["텍스트 에디터","키보드 중심","확장 가능"],p:[]},
        {n:"Emacs",v:"GNU",l:"GPL v3",t:"copyleft",u:"gnu.org/software/emacs",tags:["Editor","Lisp"],f:["확장 가능 에디터","Elisp 스크립팅","통합 환경"],p:[]},
        {n:"Atom",v:"GitHub",l:"MIT",t:"permissive",u:"atom.io",tags:["Editor","Hackable"],f:["해킹 가능 에디터","웹 기술 기반","패키지 시스템"],p:[]},
        {n:"Sublime Merge",v:"Sublime HQ",l:"Proprietary",t:"proprietary",u:"sublimemerge.com",tags:["Git","GUI"],f:["Git 클라이언트","빠른 성능","시각적 병합"],p:[]},
        {n:"GitHub Desktop",v:"GitHub",l:"MIT",t:"permissive",u:"desktop.github.com",tags:["Git","GUI"],f:["GitHub 통합","간편한 UI","크로스 플랫폼"],p:[]},
        {n:"Postman",v:"Postman",l:"Proprietary",t:"proprietary",u:"postman.com",tags:["API","Testing"],f:["API 테스팅","콜렉션 관리","자동화 테스트"],p:[]},
        {n:"JMeter",v:"Apache",l:"Apache 2.0",t:"permissive",u:"jmeter.apache.org",tags:["Testing","Performance"],f:["부하 테스트","성능 측정","다양한 프로토콜"],p:["락플레이스","오픈소스컨설팅","네오클로바","아온소프트","오케스트로"]},
        {n:"Selenium",v:"Selenium",l:"Apache 2.0",t:"permissive",u:"selenium.dev",tags:["Testing","Automation"],f:["웹 자동화","크로스 브라우저","다중 언어 지원"],p:["락플레이스"]},
        {n:"Python",v:"Python Software Foundation",l:"PSF",t:"permissive",u:"python.org",tags:["Language","프로그래밍"],f:["범용 프로그래밍 언어","풍부한 라이브러리","쉬운 문법"],p:["누리꿈소프트","두타아이티","아이오차드","헤르메시스","엑셈","와탭랩스"]},
        {n:"R",v:"R Foundation",l:"GPL v2",t:"copyleft",u:"r-project.org",tags:["Language","통계"],f:["통계 분석","데이터 시각화","패키지 생태계"],p:["누리꿈소프트","대보정보통신","비온시이노베이터","헤르메시스"]},
        {n:"Subversion",v:"Apache",l:"Apache 2.0",t:"permissive",u:"subversion.apache.org",tags:["VCS","버전관리"],f:["중앙 집중식 VCS","디렉토리 버전관리","원자적 커밋"],p:["덕풍정보기술","리브리오"]},
        {n:"eGovFrame",v:"정보통신산업진흥원",l:"Apache 2.0",t:"permissive",u:"egovframe.go.kr",tags:["Framework","국산","공공"],f:["전자정부 표준프레임워크","공공 시스템","Spring 기반"],p:["덕풍정보기술","비온시이노베이터","세림티에스지","윤커뮤니케이션즈","엑셈"]},
        {n:"Axon Framework",v:"AxonIQ",l:"Apache 2.0",t:"permissive",u:"axoniq.io",tags:["Framework","CQRS"],f:["CQRS/이벤트소싱","DDD 지원","마이크로서비스"],p:["오에스씨코리아"]},
        {n:"CKEditor",v:"CKSource",l:"GPL v2",t:"copyleft",u:"ckeditor.com",tags:["에디터","웹"],f:["위지윅 에디터","웹 텍스트 편집","플러그인 확장"],p:["대신정보통신"]},
        {n:"Essencia",v:"유엔진솔루션즈",l:"Apache 2.0",t:"permissive",u:"uengine.org",tags:["SEMAT","국산"],f:["SW공학 도구","SEMAT 커널","프로젝트 관리"],p:["유엔진솔루션즈"]},
        {n:"JDesigner Platform",v:"한국오픈솔루션",l:"Commercial",t:"proprietary",u:"kosoltech.com",tags:["개발도구","국산"],f:["저코드 플랫폼","비주얼 개발","국산"],p:["한국오픈솔루션"]},
        {n:"SmartBuilder",v:"KIC컨설팅",l:"Commercial",t:"proprietary",u:"smartbuilder.co.kr",tags:["개발도구","국산"],f:["웹 빌더","노코드/로우코드","비즈니스 앱"],p:["KIC컨설팅"]},
        {n:"K-DevPro",v:"케이티디에스",l:"Commercial",t:"proprietary",u:"ktds.com",tags:["개발도구","국산"],f:["개발 생산성","통합 개발환경","국산"],p:["케이티디에스"]},
        {n:"Spring Batch",v:"VMware",l:"Apache 2.0",t:"permissive",u:"spring.io/projects/spring-batch",tags:["Batch","Java"],f:["배치 처리 프레임워크","대용량 처리","스케줄링"],p:["케이엘정보통신","오케스트로","엑셈","티맥스소프트","와탭랩스"]}
    ],
    "웹 프레임워크": [
        {n:"Spring",v:"VMware",l:"Apache 2.0",t:"permissive",u:"spring.io",tags:["Java","Enterprise"],f:["엔터프라이즈 프레임워크","의존성 주입","풍부한 생태계"],p:["두타아이티","티맥스소프트","에스코어","엑셈","와탭랩스"]},
        {n:"Django",v:"Django Foundation",l:"BSD",t:"permissive",u:"djangoproject.com",tags:["Python","Web"],f:["풀스택 프레임워크","ORM 내장","관리자 페이지"],p:["락플레이스","아이오차드","엑셈"]},
        {n:"Flask",v:"Pallets",l:"BSD",t:"permissive",u:"flask.palletsprojects.com",tags:["Python","Micro"],f:["마이크로 프레임워크","유연한 구조","확장 가능"],p:[]},
        {n:"React",v:"Meta",l:"MIT",t:"permissive",u:"react.dev",tags:["JavaScript","Frontend"],f:["컴포넌트 기반","가상 DOM","선언적 UI"],p:["락플레이스"]},
        {n:"Vue.js",v:"Evan You",l:"MIT",t:"permissive",u:"vuejs.org",tags:["JavaScript","Frontend"],f:["점진적 프레임워크","반응형 데이터","쉬운 학습"],p:["락플레이스"]},
        {n:"Angular",v:"Google",l:"MIT",t:"permissive",u:"angular.io",tags:["TypeScript","Frontend"],f:["풀 프레임워크","양방향 바인딩","TypeScript 기반"],p:["락플레이스"]},
        {n:"Node.js",v:"OpenJS Foundation",l:"MIT",t:"permissive",u:"nodejs.org",tags:["JavaScript","Runtime"],f:["JavaScript 런타임","비동기 I/O","이벤트 기반"],p:["락플레이스","인프런","와탭랩스","생활코딩","엑셈"]},
        {n:"Express.js",v:"OpenJS Foundation",l:"MIT",t:"permissive",u:"expressjs.com",tags:["JavaScript","Backend"],f:["미니멀 프레임워크","미들웨어","유연한 라우팅"],p:[]},
        {n:"FastAPI",v:"Sebastián Ramírez",l:"MIT",t:"permissive",u:"fastapi.tiangolo.com",tags:["Python","API"],f:["고성능 API","자동 문서화","타입 힌트"],p:[]},
        {n:"Ruby on Rails",v:"Rails Core",l:"MIT",t:"permissive",u:"rubyonrails.org",tags:["Ruby","MVC"],f:["MVC 패턴","관례 우선","빠른 개발"],p:[]},
        {n:"Laravel",v:"Taylor Otwell",l:"MIT",t:"permissive",u:"laravel.com",tags:["PHP","MVC"],f:["우아한 문법","Eloquent ORM","풍부한 기능"],p:[]},
        {n:"Symfony",v:"SensioLabs",l:"MIT",t:"permissive",u:"symfony.com",tags:["PHP","Enterprise"],f:["재사용 가능 컴포넌트","유연한 구조","엔터프라이즈급"],p:[]},
        {n:"ASP.NET Core",v:"Microsoft",l:"MIT",t:"permissive",u:"dotnet.microsoft.com",tags:["C#","Web"],f:["크로스 플랫폼","고성능","클라우드 최적화"],p:[]},
        {n:"Gin",v:"Gin Community",l:"MIT",t:"permissive",u:"gin-gonic.com",tags:["Go","Web"],f:["고성능 라우터","미들웨어","JSON 처리"],p:[]},
        {n:"Echo",v:"Echo Community",l:"MIT",t:"permissive",u:"echo.labstack.com",tags:["Go","Web"],f:["경량 프레임워크","빠른 라우팅","확장성"],p:[]},
        {n:"Nest.js",v:"Nest",l:"MIT",t:"permissive",u:"nestjs.com",tags:["TypeScript","Backend"],f:["모듈형 아키텍처","의존성 주입","TypeScript 네이티브"],p:[]},
        {n:"Next.js",v:"Vercel",l:"MIT",t:"permissive",u:"nextjs.org",tags:["React","SSR"],f:["React 프레임워크","SSR/SSG","파일 기반 라우팅"],p:[]},
        {n:"Nuxt.js",v:"Nuxt",l:"MIT",t:"permissive",u:"nuxt.com",tags:["Vue","SSR"],f:["Vue 프레임워크","서버 사이드 렌더링","자동 라우팅"],p:[]},
        {n:"Svelte",v:"Rich Harris",l:"MIT",t:"permissive",u:"svelte.dev",tags:["JavaScript","Compiler"],f:["컴파일러 기반","적은 번들 크기","반응성 내장"],p:[]},
        {n:"Remix",v:"Remix",l:"MIT",t:"permissive",u:"remix.run",tags:["React","Web"],f:["풀스택 프레임워크","중첩 라우팅","데이터 로딩"],p:[]}
    ],
    "CMS/포털": [
        {n:"WordPress",v:"WordPress Foundation",l:"GPL v2",t:"copyleft",u:"wordpress.org",tags:["CMS","Blog"],f:["최대 CMS 점유율","플러그인 생태계","테마 시스템"],p:["락플레이스","오픈소스컨설팅","비씨티원"]},
        {n:"Drupal",v:"Drupal Association",l:"GPL v2",t:"copyleft",u:"drupal.org",tags:["CMS","Enterprise"],f:["엔터프라이즈급 CMS","모듈형 아키텍처","강력한 보안"],p:["락플레이스","넥스트이온","오베네프"]},
        {n:"Joomla",v:"Open Source Matters",l:"GPL v2",t:"copyleft",u:"joomla.org",tags:["CMS","PHP"],f:["사용자 친화적","확장 기능","다국어 지원"],p:[]},
        {n:"Ghost",v:"Ghost Foundation",l:"MIT",t:"permissive",u:"ghost.org",tags:["CMS","Blog"],f:["전문 블로그 플랫폼","마크다운 에디터","멤버십 기능"],p:[]},
        {n:"Strapi",v:"Strapi",l:"MIT",t:"permissive",u:"strapi.io",tags:["CMS","Headless"],f:["헤드리스 CMS","REST/GraphQL API","커스터마이징"],p:[]},
        {n:"Directus",v:"Directus",l:"GPL v3",t:"copyleft",u:"directus.io",tags:["CMS","Headless"],f:["데이터 우선 CMS","직관적 UI","DB 래퍼"],p:[]},
        {n:"Payload CMS",v:"Payload",l:"MIT",t:"permissive",u:"payloadcms.com",tags:["CMS","Headless"],f:["TypeScript 기반","로컬 API","개발자 중심"],p:[]},
        {n:"KeystoneJS",v:"Keystone",l:"MIT",t:"permissive",u:"keystonejs.com",tags:["CMS","GraphQL"],f:["GraphQL API","확장 가능","관리자 UI"],p:[]},
        {n:"Grav",v:"Grav",l:"MIT",t:"permissive",u:"getgrav.org",tags:["CMS","Flat-file"],f:["파일 기반 CMS","DB 불필요","유연한 구조"],p:[]},
        {n:"Hugo",v:"Hugo",l:"Apache 2.0",t:"permissive",u:"gohugo.io",tags:["SSG","Go"],f:["초고속 빌드","정적 사이트 생성","Go 템플릿"],p:[]},
        {n:"Jekyll",v:"Jekyll",l:"MIT",t:"permissive",u:"jekyllrb.com",tags:["SSG","Ruby"],f:["GitHub Pages 통합","Liquid 템플릿","간단한 구조"],p:[]},
        {n:"Gatsby",v:"Gatsby",l:"MIT",t:"permissive",u:"gatsbyjs.com",tags:["SSG","React"],f:["React 기반 SSG","GraphQL 데이터","플러그인 시스템"],p:[]},
        {n:"XpressEngine",v:"네이버",l:"LGPL v2.1",t:"copyleft",u:"xpressengine.io",tags:["CMS","국산","PHP"],f:["국산 CMS","모듈형 구조","커뮤니티 기능"],p:["XE커뮤니티"]},
        {n:"Rhymix",v:"Rhymix 커뮤니티",l:"GPL v2",t:"copyleft",u:"rhymix.org",tags:["CMS","국산","PHP"],f:["XE 포크","보안 강화","성능 개선"],p:["라이믹스커뮤니티"]}
    ],
    "협업/그룹웨어": [
        {n:"Nextcloud",v:"Nextcloud GmbH",l:"AGPL",t:"copyleft",u:"nextcloud.com",tags:["협업","파일공유"],f:["파일 동기화","협업 도구","자체 호스팅"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"Mattermost",v:"Mattermost Inc",l:"MIT",t:"permissive",u:"mattermost.com",tags:["협업","Chat"],f:["팀 채팅","Slack 대체","보안 중심"],p:["락플레이스"]},
        {n:"Rocket.Chat",v:"Rocket.Chat",l:"MIT",t:"permissive",u:"rocket.chat",tags:["협업","Chat"],f:["실시간 채팅","옴니채널","커스터마이징"],p:["락플레이스"]},
        {n:"Jitsi",v:"8x8",l:"Apache 2.0",t:"permissive",u:"jitsi.org",tags:["협업","Video"],f:["화상 회의","암호화 통신","웹 기반"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"Odoo",v:"Odoo SA",l:"LGPL",t:"copyleft",u:"odoo.com",tags:["ERP","CRM"],f:["통합 비즈니스 앱","모듈형 구조","CRM/ERP"],p:["오두코리아","포스원","링크업인포텍"]},
        {n:"ERPNext",v:"Frappe",l:"GPL v3",t:"copyleft",u:"erpnext.com",tags:["ERP","Business"],f:["오픈소스 ERP","제조/유통","재무 관리"],p:[]},
        {n:"Redmine",v:"Jean-Philippe Lang",l:"GPL v2",t:"copyleft",u:"redmine.org",tags:["협업","PM"],f:["프로젝트 관리","이슈 추적","간트 차트"],p:["락플레이스","오픈소스컨설팅","대신정보통신","오케스트로"]},
        {n:"Taiga",v:"Taiga Agile",l:"AGPL",t:"copyleft",u:"taiga.io",tags:["협업","Agile"],f:["애자일 관리","스크럼/칸반","사용자 스토리"],p:[]},
        {n:"Trac",v:"Edgewall",l:"BSD",t:"permissive",u:"trac.edgewall.org",tags:["협업","이슈추적"],f:["이슈 추적","위키 통합","버전 관리"],p:[]},
        {n:"Phabricator",v:"Phacility",l:"Apache 2.0",t:"permissive",u:"phacility.com",tags:["협업","코드리뷰"],f:["코드 리뷰","작업 관리","개발 도구 통합"],p:[]},
        {n:"Gitea",v:"Gitea",l:"MIT",t:"permissive",u:"gitea.io",tags:["Git","Self-hosted"],f:["경량 Git 서버","자체 호스팅","Go 기반"],p:["락플레이스"]},
        {n:"Gogs",v:"Gogs",l:"MIT",t:"permissive",u:"gogs.io",tags:["Git","Self-hosted"],f:["간단한 Git 서비스","낮은 리소스","크로스 플랫폼"],p:[]},
        {n:"Loomio",v:"Loomio",l:"AGPL",t:"copyleft",u:"loomio.com",tags:["협업","의사결정"],f:["집단 의사결정","토론 플랫폼","투표 시스템"],p:[]},
        {n:"Zulip",v:"Kandra Labs",l:"Apache 2.0",t:"permissive",u:"zulip.com",tags:["협업","Chat"],f:["스레드형 채팅","주제별 대화","검색 기능"],p:[]},
        {n:"eGroupWare",v:"eGroupWare",l:"GPL v2",t:"copyleft",u:"egroupware.org",tags:["협업","그룹웨어"],f:["웹 기반 그룹웨어","일정 관리","프로젝트 관리"],p:["오픈소스컨설팅"]},
        {n:"Process CODI",v:"유엔진솔루션즈",l:"Apache 2.0",t:"permissive",u:"uengine.org",tags:["협업","워크플로우","국산"],f:["업무 프로세스 관리","워크플로우 자동화","협업 도구"],p:["유엔진솔루션즈"]},
        {n:"Zimbra Collaboration",v:"Synacor",l:"GPL v2",t:"copyleft",u:"zimbra.com",tags:["협업","이메일"],f:["이메일 서버","캘린더","협업 스위트"],p:["리드어스"]},
        {n:"K-Orchestra",v:"케이티디에스",l:"Commercial",t:"proprietary",u:"ktds.com",tags:["협업","자동화","국산"],f:["업무 자동화","오케스트레이션","통합 관리"],p:["케이티디에스"]},
        {n:"uEngine BPM",v:"유엔진솔루션즈",l:"Apache 2.0",t:"permissive",u:"uengine.org",tags:["BPM","워크플로우","국산"],f:["비즈니스 프로세스 관리","워크플로우 엔진","BPMN 2.0"],p:["유엔진솔루션즈"]},
        {n:"Apache OFBiz",v:"Apache",l:"Apache 2.0",t:"permissive",u:"ofbiz.apache.org",tags:["ERP","CRM"],f:["오픈소스 ERP","전자상거래","비즈니스 자동화"],p:["노블시스템"]}
    ],
    "보안": [
        {n:"OWASP ZAP",v:"OWASP",l:"Apache 2.0",t:"permissive",u:"zaproxy.org",tags:["보안","테스트"],f:["웹 취약점 스캐너","능동/수동 스캔","자동화 테스트"],p:["락플레이스","오픈소스컨설팅","스패로우"]},
        {n:"Suricata",v:"OISF",l:"GPL v2",t:"copyleft",u:"suricata.io",tags:["보안","IDS"],f:["침입 탐지/방지","멀티 스레드","네트워크 모니터링"],p:["락플레이스","시큐아이"]},
        {n:"Snort",v:"Cisco",l:"GPL v2",t:"copyleft",u:"snort.org",tags:["보안","IDS"],f:["실시간 트래픽 분석","패킷 로깅","침입 탐지"],p:["락플레이스","시큐아이"]},
        {n:"Wazuh",v:"Wazuh Inc",l:"GPL v2",t:"copyleft",u:"wazuh.com",tags:["보안","SIEM"],f:["보안 모니터링","위협 탐지","컴플라이언스"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"OpenVAS",v:"Greenbone",l:"GPL",t:"copyleft",u:"openvas.org",tags:["보안","취약점"],f:["취약점 스캐닝","포괄적 테스트","정기 업데이트"],p:["락플레이스"]},
        {n:"Keycloak",v:"Red Hat",l:"Apache 2.0",t:"permissive",u:"keycloak.org",tags:["보안","IAM"],f:["ID 및 액세스 관리","SSO 지원","다중 프로토콜"],p:["서진디에스에이","오에스씨코리아"]},
        {n:"Vault",v:"HashiCorp",l:"MPL",t:"copyleft",u:"vaultproject.io",tags:["보안","Secret"],f:["비밀 정보 관리","동적 시크릿","암호화 서비스"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"Wireshark",v:"Wireshark Foundation",l:"GPL v2",t:"copyleft",u:"wireshark.org",tags:["보안","Network"],f:["네트워크 분석","패킷 캡처","프로토콜 디코딩"],p:[]},
        {n:"Nmap",v:"Nmap Project",l:"GPL",t:"copyleft",u:"nmap.org",tags:["보안","포트스캔"],f:["포트 스캐닝","네트워크 탐색","OS 감지"],p:[]},
        {n:"Metasploit",v:"Rapid7",l:"BSD",t:"permissive",u:"metasploit.com",tags:["보안","침투테스트"],f:["침투 테스트 프레임워크","익스플로잇 개발","보안 평가"],p:[]},
        {n:"Kali Linux",v:"Offensive Security",l:"GPL",t:"copyleft",u:"kali.org",tags:["보안","침투테스트"],f:["보안 테스트 OS","600+ 도구","디지털 포렌식"],p:[]},
        {n:"OpenSSL",v:"OpenSSL Project",l:"Apache 2.0",t:"permissive",u:"openssl.org",tags:["보안","암호화"],f:["SSL/TLS 라이브러리","암호화 툴킷","표준 프로토콜"],p:[]},
        {n:"Fail2ban",v:"Fail2ban",l:"GPL v2",t:"copyleft",u:"fail2ban.org",tags:["보안","방어"],f:["침입 방지","자동 차단","로그 모니터링"],p:[]},
        {n:"ClamAV",v:"Cisco",l:"GPL v2",t:"copyleft",u:"clamav.net",tags:["보안","백신"],f:["오픈소스 백신","멀웨어 탐지","명령줄 스캐너"],p:["락플레이스"]},
        {n:"OSSEC",v:"Trend Micro",l:"GPL v2",t:"copyleft",u:"ossec.net",tags:["보안","HIDS"],f:["호스트 침입 탐지","로그 분석","파일 무결성"],p:["락플레이스"]},
        {n:"PacketFence",v:"Inverse",l:"GPL v2",t:"copyleft",u:"packetfence.org",tags:["보안","NAC"],f:["네트워크 접근 제어","BYOD 관리","유무선 통합"],p:["락플레이스"]},
        {n:"freeIPA",v:"Red Hat",l:"GPL v3",t:"copyleft",u:"freeipa.org",tags:["보안","IAM"],f:["통합 ID 관리","LDAP/Kerberos","Linux 인증"],p:["서진디에스에이"]},
        {n:"OpenLDAP",v:"OpenLDAP Foundation",l:"OpenLDAP",t:"permissive",u:"openldap.org",tags:["보안","디렉토리"],f:["디렉토리 서비스","LDAP 구현","경량 프로토콜"],p:["서진디에스에이"]},
        {n:"389 Directory Server",v:"Red Hat",l:"GPL v2",t:"copyleft",u:"directory.fedoraproject.org",tags:["보안","디렉토리"],f:["엔터프라이즈 LDAP","복제 지원","웹 콘솔"],p:["서진디에스에이"]},
        {n:"ModSecurity",v:"Trustwave",l:"Apache 2.0",t:"permissive",u:"modsecurity.org",tags:["보안","WAF"],f:["웹 애플리케이션 방화벽","실시간 모니터링","규칙 기반 방어"],p:["마루인터넷","아이오차드"]},
        {n:"WSO2",v:"WSO2",l:"Apache 2.0",t:"permissive",u:"wso2.com",tags:["보안","API"],f:["API 관리","통합 플랫폼","ID 관리"],p:["오에스씨코리아","에스코어"]},
        {n:"AccessWall",v:"진테크이엔지",l:"Commercial",t:"proprietary",u:"jintech.co.kr",tags:["보안","접근제어","국산"],f:["네트워크 접근제어","보안 관리","정책 기반"],p:["진테크이엔지","에이온","에스앤에이치테크","키타스이앤지"]},
        {n:"ForgeRock",v:"ForgeRock",l:"Commercial",t:"proprietary",u:"forgerock.com",tags:["보안","IAM"],f:["ID 플랫폼","디지털 ID","액세스 관리"],p:["파로스인포"]},
        {n:"NexR Enterprise Anonymous",v:"케이티넥스알",l:"Commercial",t:"proprietary",u:"ktnexr.co.kr",tags:["보안","익명화","국산"],f:["데이터 익명화","개인정보 보호","엔터프라이즈"],p:["케이티넥스알"]}
    ],
    "모니터링/로깅": [
        {n:"Prometheus",v:"CNCF",l:"Apache 2.0",t:"permissive",u:"prometheus.io",tags:["모니터링","Metrics"],f:["메트릭 수집","시계열 DB","알림 시스템"],p:["락플레이스","오픈소스컨설팅","맨텍"]},
        {n:"Grafana",v:"Grafana Labs",l:"AGPL",t:"copyleft",u:"grafana.com",tags:["모니터링","시각화"],f:["데이터 시각화","대시보드 구성","다중 데이터소스"],p:["락플레이스","오픈소스컨설팅","맨텍"]},
        {n:"Zabbix",v:"Zabbix LLC",l:"GPL v2",t:"copyleft",u:"zabbix.com",tags:["모니터링","Enterprise"],f:["엔터프라이즈 모니터링","에이전트/에이전트리스","자동 발견"],p:["아이오차드","에스유소프트","젠탑테크놀로지","케이티디에스"]},
        {n:"Nagios",v:"Nagios Enterprises",l:"GPL v2",t:"copyleft",u:"nagios.org",tags:["모니터링","Alerting"],f:["인프라 모니터링","플러그인 확장","알림 시스템"],p:["네오클로바","락플레이스"]},
        {n:"Elasticsearch",v:"Elastic",l:"SSPL",t:"copyleft",u:"elastic.co",tags:["로깅","Search"],f:["전문 검색 엔진","분산 아키텍처","실시간 분석"],p:["락플레이스","오픈소스컨설팅","맨텍","엘라스틱코리아"]},
        {n:"Logstash",v:"Elastic",l:"SSPL",t:"copyleft",u:"elastic.co/logstash",tags:["로깅","Pipeline"],f:["로그 수집/파싱","데이터 변환","다양한 입출력"],p:["락플레이스","오픈소스컨설팅","엘라스틱코리아"]},
        {n:"Kibana",v:"Elastic",l:"SSPL",t:"copyleft",u:"elastic.co/kibana",tags:["로깅","시각화"],f:["로그 시각화","대시보드","데이터 탐색"],p:["락플레이스","오픈소스컨설팅","엘라스틱코리아","아이오차드","클루커스","오에스씨코리아","에스코어"]},
        {n:"Graylog",v:"Graylog Inc",l:"SSPL",t:"copyleft",u:"graylog.org",tags:["로깅","분석"],f:["로그 관리","중앙 집중식","알림 규칙"],p:["락플레이스"]},
        {n:"Fluentd",v:"CNCF",l:"Apache 2.0",t:"permissive",u:"fluentd.org",tags:["로깅","Collector"],f:["통합 로깅 레이어","플러그인 생태계","메모리 버퍼링"],p:["락플레이스","오픈소스컨설팅","클루커스","오에스씨코리아"]},
        {n:"Loki",v:"Grafana Labs",l:"AGPL",t:"copyleft",u:"grafana.com/loki",tags:["로깅","Prometheus-like"],f:["로그 집계","Prometheus 통합","라벨 기반 인덱싱"],p:["락플레이스"]},
        {n:"Jaeger",v:"CNCF",l:"Apache 2.0",t:"permissive",u:"jaegertracing.io",tags:["Tracing","APM"],f:["분산 추적","성능 모니터링","의존성 분석"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"Zipkin",v:"OpenZipkin",l:"Apache 2.0",t:"permissive",u:"zipkin.io",tags:["Tracing","APM"],f:["분산 시스템 추적","레이턴시 분석","서비스 의존성"],p:["락플레이스"]},
        {n:"Netdata",v:"Netdata",l:"GPL v3",t:"copyleft",u:"netdata.cloud",tags:["모니터링","실시간"],f:["실시간 모니터링","자동 탐지","경량 에이전트"],p:[]},
        {n:"Icinga",v:"Icinga",l:"GPL v2",t:"copyleft",u:"icinga.com",tags:["모니터링","Nagios-fork"],f:["Nagios 호환","REST API","확장 가능"],p:["락플레이스"]},
        {n:"Scouter",v:"LG CNS",l:"Apache 2.0",t:"permissive",u:"github.com/scouter-project/scouter",tags:["APM","국산","모니터링"],f:["국산 APM","실시간 모니터링","Java 전문"],p:["LG CNS","오픈소스컨설팅","에스코어"]},
        {n:"K-Watch SMS",v:"케이티디에스",l:"Commercial",t:"proprietary",u:"ktds.com",tags:["모니터링","국산"],f:["시스템 모니터링","알림 관리","성능 분석"],p:["케이티디에스","에스유소프트"]}
    ],
    "자동화/IaC": [
        {n:"Ansible",v:"Red Hat",l:"GPL v3",t:"copyleft",u:"ansible.com",tags:["자동화","구성관리"],f:["에이전트리스","YAML 기반","멱등성 보장"],p:["락플레이스","레드햇","리눅스데이타시스템","아이오차드","영우디지탈","오뉴이노베이션","이테크시스템","코오롱베니트","오케스트로","이액티브"]},
        {n:"Terraform",v:"HashiCorp",l:"MPL",t:"copyleft",u:"terraform.io",tags:["IaC","멀티클라우드"],f:["인프라 코드화","선언적 구성","상태 관리"],p:["에스코어"]},
        {n:"Puppet",v:"Puppet",l:"Apache 2.0",t:"permissive",u:"puppet.com",tags:["자동화","구성관리"],f:["구성 관리","모델 기반","대규모 자동화"],p:["락플레이스"]},
        {n:"Chef",v:"Progress",l:"Apache 2.0",t:"permissive",u:"chef.io",tags:["자동화","구성관리"],f:["인프라 자동화","Ruby DSL","쿡북 관리"],p:["락플레이스"]},
        {n:"SaltStack",v:"VMware",l:"Apache 2.0",t:"permissive",u:"saltproject.io",tags:["자동화","Event-driven"],f:["이벤트 기반","원격 실행","확장 가능"],p:["락플레이스"]},
        {n:"Pulumi",v:"Pulumi",l:"Apache 2.0",t:"permissive",u:"pulumi.com",tags:["IaC","프로그래밍"],f:["실제 프로그래밍 언어","클라우드 네이티브","상태 관리"],p:[]},
        {n:"CloudFormation",v:"AWS",l:"Proprietary",t:"proprietary",u:"aws.amazon.com/cloudformation",tags:["IaC","AWS"],f:["AWS 전용 IaC","JSON/YAML 템플릿","스택 관리"],p:["AWS코리아"]},
        {n:"Packer",v:"HashiCorp",l:"MPL",t:"copyleft",u:"packer.io",tags:["자동화","이미지빌드"],f:["이미지 자동화","멀티 플랫폼","템플릿 기반"],p:["락플레이스"]},
        {n:"Vagrant",v:"HashiCorp",l:"MIT",t:"permissive",u:"vagrantup.com",tags:["자동화","VM"],f:["개발 환경 관리","VM 자동화","프로비저닝"],p:["락플레이스"]},
        {n:"CFEngine",v:"CFEngine",l:"GPL v3",t:"copyleft",u:"cfengine.com",tags:["자동화","구성관리"],f:["경량 에이전트","자율적 관리","고속 실행"],p:[]},
        {n:"PaceMaker",v:"ClusterLabs",l:"GPL v2",t:"copyleft",u:"clusterlabs.org/pacemaker",tags:["HA","클러스터"],f:["고가용성 클러스터","리소스 관리","페일오버"],p:["그로윈","네오클로바","아온소프트","아이오차드","이액티브"]},
        {n:"Corosync",v:"Corosync",l:"BSD",t:"permissive",u:"corosync.github.io/corosync",tags:["HA","클러스터"],f:["클러스터 통신","멤버십 관리","HA 기반"],p:["그로윈","아온소프트","아이오차드"]},
        {n:"DRBD",v:"LINBIT",l:"GPL v2",t:"copyleft",u:"linbit.com/drbd",tags:["스토리지","복제"],f:["블록 복제","고가용성","동기화"],p:["그로윈","아온소프트","에스코어"]},
        {n:"Galera Cluster",v:"Codership",l:"GPL v2",t:"copyleft",u:"galeracluster.com",tags:["데이터베이스","HA"],f:["동기 복제","멀티 마스터","MySQL/MariaDB"],p:["그로윈","뉴런시스템","락플레이스","리브리오","아온소프트"]},
        {n:"BSR",v:"맨텍",l:"GPL",t:"copyleft",u:"mantech.co.kr",tags:["스토리지","복제","국산"],f:["블록 동기 복제","DR 솔루션","고가용성"],p:["맨텍"]},
        {n:"WDRBD",v:"맨텍",l:"GPL",t:"copyleft",u:"mantech.co.kr",tags:["스토리지","Windows","국산"],f:["Windows용 DRBD","블록 복제","HA"],p:["맨텍"]},
        {n:"Cacti",v:"The Cacti Group",l:"GPL v2",t:"copyleft",u:"cacti.net",tags:["모니터링","RRDtool"],f:["네트워크 그래프","RRDtool 프론트엔드","SNMP 모니터링"],p:["네오클로바"]},
        {n:"Heartbeat",v:"Linux-HA",l:"GPL v2",t:"copyleft",u:"linux-ha.org",tags:["HA","클러스터"],f:["고가용성","클러스터 관리","페일오버"],p:["뉴런시스템","아온소프트"]},
        {n:"LSCP",v:"에스유소프트",l:"Commercial",t:"proprietary",u:"sulinux.net",tags:["관리","국산"],f:["리눅스 서버 관리","자원 모니터링","통합 관리"],p:["에스유소프트"]},
        {n:"LSMP",v:"에스유소프트",l:"Commercial",t:"proprietary",u:"sulinux.net",tags:["관리","국산"],f:["리눅스 서버 관리","패키지 관리","통합 모니터링"],p:["에스유소프트"]},
        {n:"SeOA",v:"세림티에스지",l:"Commercial",t:"proprietary",u:"srtsg.co.kr",tags:["자원관리","국산"],f:["시스템 운영 자동화","자원 관리","모니터링"],p:["세림티에스지"]},
        {n:"Samba",v:"Samba Team",l:"GPL v3",t:"copyleft",u:"samba.org",tags:["파일공유","Windows호환"],f:["SMB/CIFS 구현","Windows 네트워크 호환","파일 공유"],p:["에스유소프트"]}
    ],
    "메시징": [
        {n:"Kafka",v:"Apache",l:"Apache 2.0",t:"permissive",u:"kafka.apache.org",tags:["메시징","Stream"],f:["분산 스트리밍","높은 처리량","내구성 보장"],p:["락플레이스","오픈소스컨설팅","컨플루언트","맨텍"]},
        {n:"RabbitMQ",v:"VMware",l:"MPL",t:"copyleft",u:"rabbitmq.com",tags:["메시징","AMQP"],f:["메시지 브로커","다양한 프로토콜","유연한 라우팅"],p:["락플레이스","오픈소스컨설팅","맨텍","에스코어"]},
        {n:"Pulsar",v:"Apache",l:"Apache 2.0",t:"permissive",u:"pulsar.apache.org",tags:["메시징","Cloud"],f:["클라우드 네이티브","멀티 테넌시","계층형 스토리지"],p:["락플레이스"]},
        {n:"NATS",v:"CNCF",l:"Apache 2.0",t:"permissive",u:"nats.io",tags:["메시징","경량"],f:["경량 메시징","고성능","간단한 API"],p:["락플레이스"]},
        {n:"ActiveMQ",v:"Apache",l:"Apache 2.0",t:"permissive",u:"activemq.apache.org",tags:["메시징","JMS"],f:["JMS 구현","다양한 프로토콜","엔터프라이즈급"],p:["락플레이스","오픈소스컨설팅","핀스정보기술"]},
        {n:"ZeroMQ",v:"ZeroMQ",l:"MPL",t:"copyleft",u:"zeromq.org",tags:["메시징","고성능"],f:["비동기 메시징","소켓 라이브러리","브로커리스"],p:[]},
        {n:"Apache Qpid",v:"Apache",l:"Apache 2.0",t:"permissive",u:"qpid.apache.org",tags:["메시징","AMQP"],f:["AMQP 메시징","크로스 플랫폼","다중 언어"],p:[]},
        {n:"EMQX",v:"EMQ",l:"Apache 2.0",t:"permissive",u:"emqx.io",tags:["메시징","MQTT"],f:["MQTT 브로커","IoT 최적화","고확장성"],p:["락플레이스"]},
        {n:"VerneMQ",v:"VerneMQ",l:"Apache 2.0",t:"permissive",u:"vernemq.com",tags:["메시징","MQTT"],f:["분산 MQTT 브로커","클러스터링","플러그인 확장"],p:[]},
        {n:"Camel",v:"Apache",l:"Apache 2.0",t:"permissive",u:"camel.apache.org",tags:["통합","EIP"],f:["엔터프라이즈 통합","EIP 패턴","다양한 커넥터"],p:["핀스정보기술","엑셈"]},
        {n:"LVS",v:"LinuxVirtualServer",l:"GPL v2",t:"copyleft",u:"linuxvirtualserver.org",tags:["로드밸런싱","서버"],f:["리눅스 가상 서버","L4 로드밸런싱","고가용성"],p:["뉴런시스템"]},
        {n:"OCFS2",v:"Oracle",l:"GPL v2",t:"copyleft",u:"oracle.com/linux/ocfs2",tags:["클러스터","파일시스템"],f:["클러스터 파일시스템","공유 스토리지","Oracle 최적화"],p:["아이오차드"]},
        {n:"Red Hat GFS",v:"Red Hat",l:"GPL v2",t:"copyleft",u:"redhat.com",tags:["클러스터","파일시스템"],f:["글로벌 파일시스템","클러스터 스토리지","HA 지원"],p:["락플레이스","세림티에스지"]}
    ],
    "미디어/그래픽": [
        {n:"Blender",v:"Blender Foundation",l:"GPL v3",t:"copyleft",u:"blender.org",tags:["3D","모델링"],f:["3D 제작 도구","모델링/애니메이션","렌더링 엔진"],p:[]},
        {n:"GIMP",v:"GIMP Team",l:"GPL v3",t:"copyleft",u:"gimp.org",tags:["그래픽","편집"],f:["이미지 편집","레이어 지원","플러그인 확장"],p:[]},
        {n:"Inkscape",v:"Inkscape Project",l:"GPL v3",t:"copyleft",u:"inkscape.org",tags:["그래픽","벡터"],f:["벡터 그래픽","SVG 편집","드로잉 도구"],p:[]},
        {n:"Krita",v:"KDE",l:"GPL v3",t:"copyleft",u:"krita.org",tags:["그래픽","페인팅"],f:["디지털 페인팅","브러시 엔진","애니메이션"],p:[]},
        {n:"FFmpeg",v:"FFmpeg Team",l:"LGPL",t:"copyleft",u:"ffmpeg.org",tags:["미디어","Video"],f:["멀티미디어 프레임워크","코덱 라이브러리","포맷 변환"],p:[]},
        {n:"VLC",v:"VideoLAN",l:"GPL v2",t:"copyleft",u:"videolan.org",tags:["미디어","Player"],f:["미디어 플레이어","모든 포맷 지원","스트리밍"],p:[]},
        {n:"OBS Studio",v:"OBS Project",l:"GPL v2",t:"copyleft",u:"obsproject.com",tags:["미디어","방송"],f:["실시간 방송","화면 녹화","스트리밍"],p:[]},
        {n:"Audacity",v:"Audacity Team",l:"GPL v2",t:"copyleft",u:"audacityteam.org",tags:["오디오","편집"],f:["오디오 편집","멀티트랙","효과 처리"],p:[]},
        {n:"Kdenlive",v:"KDE",l:"GPL v3",t:"copyleft",u:"kdenlive.org",tags:["비디오","편집"],f:["비디오 편집","타임라인","효과/전환"],p:[]},
        {n:"OpenShot",v:"OpenShot Studios",l:"GPL v3",t:"copyleft",u:"openshot.org",tags:["비디오","편집"],f:["사용자 친화적","3D 애니메이션","무제한 트랙"],p:[]},
        {n:"DaVinci Resolve",v:"Blackmagic",l:"Proprietary",t:"proprietary",u:"blackmagicdesign.com",tags:["비디오","전문편집"],f:["전문 편집","컬러 그레이딩","VFX"],p:[]},
        {n:"Shotcut",v:"Meltytech",l:"GPL v3",t:"copyleft",u:"shotcut.org",tags:["비디오","편집"],f:["크로스 플랫폼","네이티브 편집","필터 지원"],p:[]},
        {n:"Hamonia MediaWeaver",v:"인베슘",l:"Commercial",t:"proprietary",u:"invesume.com",tags:["영상처리","미디어","국산"],f:["미디어 처리","영상 관리","인코딩"],p:["인베슘"]},
        {n:"FastCatSearch",v:"지앤클라우드",l:"Apache 2.0",t:"permissive",u:"gcloud.co.kr",tags:["검색엔진","국산"],f:["검색엔진","자연어 처리","텍스트 분석"],p:["지앤클라우드"]}
    ],
    "IoT/엣지": [
        {n:"Mosquitto",v:"Eclipse",l:"EPL",t:"permissive",u:"mosquitto.org",tags:["IoT","MQTT"],f:["경량 MQTT 브로커","IoT 메시징","낮은 리소스"],p:["락플레이스"]},
        {n:"Node-RED",v:"OpenJS Foundation",l:"Apache 2.0",t:"permissive",u:"nodered.org",tags:["IoT","Flow"],f:["플로우 기반 프로그래밍","비주얼 와이어링","IoT 통합"],p:["락플레이스"]},
        {n:"ThingsBoard",v:"ThingsBoard Inc",l:"Apache 2.0",t:"permissive",u:"thingsboard.io",tags:["IoT","Platform"],f:["IoT 플랫폼","디바이스 관리","데이터 시각화"],p:["락플레이스"]},
        {n:"Home Assistant",v:"Home Assistant",l:"Apache 2.0",t:"permissive",u:"home-assistant.io",tags:["IoT","Home"],f:["홈 자동화","2000+ 통합","프라이버시 중심"],p:[]},
        {n:"EdgeX Foundry",v:"Linux Foundation",l:"Apache 2.0",t:"permissive",u:"edgexfoundry.org",tags:["IoT","Edge"],f:["엣지 컴퓨팅","마이크로서비스","벤더 중립"],p:["락플레이스"]},
        {n:"KubeEdge",v:"CNCF",l:"Apache 2.0",t:"permissive",u:"kubeedge.io",tags:["IoT","K8s"],f:["K8s 엣지 확장","클라우드-엣지 동기화","경량 런타임"],p:["락플레이스"]},
        {n:"OpenThread",v:"Google",l:"BSD",t:"permissive",u:"openthread.io",tags:["IoT","Mesh"],f:["Thread 네트워킹","메시 프로토콜","저전력"],p:[]},
        {n:"Zephyr",v:"Linux Foundation",l:"Apache 2.0",t:"permissive",u:"zephyrproject.org",tags:["IoT","RTOS"],f:["실시간 OS","모듈형 커널","보드 지원"],p:[]},
        {n:"FreeRTOS",v:"Amazon",l:"MIT",t:"permissive",u:"freertos.org",tags:["IoT","RTOS"],f:["실시간 커널","임베디드 시스템","AWS 통합"],p:[]},
        {n:"RIOT OS",v:"RIOT",l:"LGPL",t:"copyleft",u:"riot-os.org",tags:["IoT","OS"],f:["IoT 운영체제","표준 API","네트워크 스택"],p:[]}
    ],
    "블록체인": [
        {n:"Ethereum",v:"Ethereum Foundation",l:"GPL v3",t:"copyleft",u:"ethereum.org",tags:["블록체인","스마트컨트랙트"],f:["스마트 컨트랙트","탈중앙화 앱","EVM"],p:["블로코","헥슬란트"]},
        {n:"Bitcoin Core",v:"Bitcoin",l:"MIT",t:"permissive",u:"bitcoin.org",tags:["블록체인","암호화폐"],f:["암호화폐","P2P 네트워크","작업 증명"],p:[]},
        {n:"Hyperledger Fabric",v:"Linux Foundation",l:"Apache 2.0",t:"permissive",u:"hyperledger.org/fabric",tags:["블록체인","Enterprise"],f:["프라이빗 블록체인","모듈형 아키텍처","엔터프라이즈급"],p:["블로코","아이콘루프","삼성SDS"]},
        {n:"Hyperledger Besu",v:"Linux Foundation",l:"Apache 2.0",t:"permissive",u:"hyperledger.org/besu",tags:["블록체인","Ethereum"],f:["엔터프라이즈 이더리움","퍼블릭/프라이빗","PoA 합의"],p:["블로코"]},
        {n:"Quorum",v:"ConsenSys",l:"Apache 2.0",t:"permissive",u:"consensys.net/quorum",tags:["블록체인","Enterprise"],f:["프라이빗 트랜잭션","고성능","기업용 이더리움"],p:[]},
        {n:"Corda",v:"R3",l:"Apache 2.0",t:"permissive",u:"corda.net",tags:["블록체인","금융"],f:["금융 특화","프라이버시","스마트 컨트랙트"],p:[]},
        {n:"IPFS",v:"Protocol Labs",l:"MIT",t:"permissive",u:"ipfs.tech",tags:["블록체인","Storage"],f:["분산 파일 시스템","콘텐츠 주소 지정","P2P 스토리지"],p:[]},
        {n:"Polkadot",v:"Web3 Foundation",l:"GPL v3",t:"copyleft",u:"polkadot.network",tags:["블록체인","멀티체인"],f:["멀티체인 플랫폼","상호 운용성","파라체인"],p:[]},
        {n:"ICON",v:"아이콘루프",l:"Apache 2.0",t:"permissive",u:"icon.foundation",tags:["블록체인","국산"],f:["국산 블록체인","크로스체인","DID 지원"],p:["아이콘루프"]}
    ],
    "가상화": [
        {n:"KVM",v:"Red Hat",l:"GPL v2",t:"copyleft",u:"linux-kvm.org",tags:["가상화","Hypervisor"],f:["커널 기반 가상화","전가상화","Linux 통합"],p:["그로윈","락플레이스","메타비즈","아온소프트","아이오차드","에스유소프트","오케스트로","지앤에스인포"]},
        {n:"Proxmox",v:"Proxmox",l:"AGPL",t:"copyleft",u:"proxmox.com",tags:["가상화","Container"],f:["가상화 플랫폼","KVM+LXC","웹 관리"],p:["락플레이스"]},
        {n:"oVirt",v:"Red Hat",l:"Apache 2.0",t:"permissive",u:"ovirt.org",tags:["가상화","Management"],f:["가상화 관리","RHEV 업스트림","웹 콘솔"],p:["락플레이스","레드햇코리아"]},
        {n:"Xen",v:"Linux Foundation",l:"GPL v2",t:"copyleft",u:"xenproject.org",tags:["가상화","Hypervisor"],f:["Type-1 하이퍼바이저","반가상화","클라우드 기반"],p:["아이오차드"]},
        {n:"QEMU",v:"QEMU",l:"GPL v2",t:"copyleft",u:"qemu.org",tags:["가상화","Emulator"],f:["하드웨어 에뮬레이션","다양한 아키텍처","KVM 연동"],p:["락플레이스"]},
        {n:"VirtualBox",v:"Oracle",l:"GPL v2",t:"copyleft",u:"virtualbox.org",tags:["가상화","Desktop"],f:["데스크톱 가상화","크로스 플랫폼","스냅샷"],p:[]}
    ],
    "스토리지": [
        {n:"Ceph",v:"Red Hat",l:"LGPL",t:"copyleft",u:"ceph.io",tags:["스토리지","분산"],f:["분산 스토리지","오브젝트/블록/파일","자가 치유"],p:["그로윈","락플레이스","아이오차드","오케스트로","오픈소스컨설팅"]},
        {n:"GlusterFS",v:"Red Hat",l:"GPL v3",t:"copyleft",u:"gluster.org",tags:["스토리지","분산"],f:["분산 파일시스템","확장성","복제"],p:["그로윈","뉴런시스템","아이오차드"]},
        {n:"MinIO",v:"MinIO",l:"AGPL",t:"copyleft",u:"min.io",tags:["스토리지","Object"],f:["오브젝트 스토리지","S3 호환","고성능"],p:["락플레이스","오픈소스컨설팅"]},
        {n:"OpenZFS",v:"OpenZFS",l:"CDDL",t:"permissive",u:"openzfs.org",tags:["스토리지","파일시스템"],f:["고급 파일시스템","스냅샷","데이터 무결성"],p:["락플레이스"]},
        {n:"Longhorn",v:"SUSE",l:"Apache 2.0",t:"permissive",u:"longhorn.io",tags:["스토리지","K8s"],f:["K8s 스토리지","분산 블록","백업/복구"],p:["수세코리아","락플레이스"]}
    ],
    "오피스/문서": [
        {n:"LibreOffice",v:"The Document Foundation",l:"MPL",t:"copyleft",u:"libreoffice.org",tags:["오피스","문서"],f:["오피스 제품군","MS오피스 호환","크로스 플랫폼"],p:["한컴위드","락플레이스"]},
        {n:"OnlyOffice",v:"Ascensio System",l:"AGPL",t:"copyleft",u:"onlyoffice.com",tags:["오피스","협업"],f:["온라인 오피스","실시간 협업","MS호환"],p:["오픈소스컨설팅"]},
        {n:"한컴오피스",v:"한글과컴퓨터",l:"Commercial",t:"proprietary",u:"hancom.com",tags:["오피스","국산"],f:["국산 오피스","한글 문서","공공기관 표준"],p:["한글과컴퓨터"]}
    ],
    "GIS/공간정보": [
        {n:"GeoServer",v:"GeoServer",l:"GPL v2",t:"copyleft",u:"geoserver.org",tags:["GIS","지도"],f:["지리 데이터 서버","OGC 표준","웹 지도"],p:["가이아쓰리디","망고시스템","웨이버스","헤르메시스"]},
        {n:"PostGIS",v:"PostGIS",l:"GPL v2",t:"copyleft",u:"postgis.net",tags:["GIS","데이터베이스"],f:["공간 데이터베이스","PostgreSQL 확장","지리 분석"],p:["가이아쓰리디","망고시스템","웨이버스","지오로그","헤르메시스","EDB"]},
        {n:"QGIS",v:"QGIS",l:"GPL v2",t:"copyleft",u:"qgis.org",tags:["GIS","Desktop"],f:["데스크톱 GIS","데이터 시각화","분석 도구"],p:["가이아쓰리디","망고시스템","지오로그","포스웨이브","헤르메시스"]},
        {n:"OpenLayers",v:"OpenLayers",l:"BSD",t:"permissive",u:"openlayers.org",tags:["GIS","웹지도"],f:["웹 지도 라이브러리","타일 지도","상호작용"],p:["가이아쓰리디","망고시스템","웨이버스","헤르메시스"]},
        {n:"mago3D",v:"가이아쓰리디",l:"Apache 2.0",t:"permissive",u:"mago3d.com",tags:["GIS","3D","국산"],f:["3D GIS 플랫폼","대용량 3D","웹 기반"],p:["가이아쓰리디"]},
        {n:"gPocket",v:"망고시스템",l:"GPL v2",t:"copyleft",u:"mangosystem.com",tags:["GIS","모바일","국산"],f:["모바일 GIS","현장 조사","공간분석"],p:["망고시스템"]},
        {n:"Grid Rainfall Runoff Model",v:"헤르메시스",l:"GPL",t:"copyleft",u:"hermesys.co.kr",tags:["GIS","수문분석","국산"],f:["강우 유출 모델","수문 분석","격자 기반"],p:["헤르메시스"]},
        {n:"OpenGXT",v:"망고시스템",l:"GPL v2",t:"copyleft",u:"mangosystem.com",tags:["GIS","공간분석","국산"],f:["공간분석 도구","GeoServer 확장","오픈소스"],p:["망고시스템"]},
        {n:"PINOGIO",v:"망고시스템",l:"GPL v2",t:"copyleft",u:"mangosystem.com",tags:["GIS","국산"],f:["GIS 포털","공간정보 관리","데이터 통합"],p:["망고시스템"]}
    ],
    "LMS/교육": [
        {n:"Moodle",v:"Moodle",l:"GPL v3",t:"copyleft",u:"moodle.org",tags:["LMS","교육"],f:["학습 관리 시스템","강좌 관리","온라인 학습"],p:["지노테크"]},
        {n:"Open edX",v:"edX",l:"AGPL",t:"copyleft",u:"openedx.org",tags:["LMS","MOOC"],f:["MOOC 플랫폼","대규모 온라인 교육","코스웨어"],p:["오베네프"]},
        {n:"Hamonia ClassMate",v:"인베슘",l:"Commercial",t:"proprietary",u:"invesume.com",tags:["LMS","국산"],f:["국산 LMS","온라인 교육","학습 관리"],p:["인베슘"]}
    ],
    "CFD/공학": [
        {n:"OpenFOAM",v:"OpenFOAM Foundation",l:"GPL v3",t:"copyleft",u:"openfoam.org",tags:["CFD","공학"],f:["전산유체역학","시뮬레이션","오픈소스 해석"],p:["넥스트폼"]},
        {n:"BARAM",v:"넥스트폼",l:"GPL v3",t:"copyleft",u:"nextfoam.co.kr",tags:["CFD","공학","국산"],f:["OpenFOAM 기반","GUI 제공","국산 CFD"],p:["넥스트폼"]}
    ],
    "라이선스검증/보안분석": [
        {n:"Black Duck",v:"Synopsys",l:"Commercial",t:"proprietary",u:"synopsys.com/software-integrity/security-testing/software-composition-analysis.html",tags:["SCA","라이선스","보안"],f:["오픈소스 분석","라이선스 검증","취약점 탐지"],p:["엘에스웨어"]},
        {n:"Coverity",v:"Synopsys",l:"Commercial",t:"proprietary",u:"synopsys.com/software-integrity/security-testing/static-analysis-sast.html",tags:["SAST","정적분석","보안"],f:["정적 코드 분석","보안 취약점","코드 품질"],p:["엘에스웨어"]},
        {n:"Defensics",v:"Synopsys",l:"Commercial",t:"proprietary",u:"synopsys.com/software-integrity/security-testing/fuzz-testing.html",tags:["Fuzzing","보안테스트"],f:["퍼징 테스트","프로토콜 테스트","보안 취약점 발견"],p:["엘에스웨어"]},
        {n:"Seeker",v:"Synopsys",l:"Commercial",t:"proprietary",u:"synopsys.com/software-integrity/security-testing/interactive-application-security-testing.html",tags:["IAST","동적분석","보안"],f:["대화형 보안 테스트","런타임 분석","취약점 탐지"],p:["엘에스웨어"]},
        {n:"WhiteHat",v:"Synopsys",l:"Commercial",t:"proprietary",u:"synopsys.com/software-integrity/security-testing/dast.html",tags:["DAST","동적분석","보안"],f:["동적 보안 테스트","웹 취약점 스캔","자동화 테스트"],p:["엘에스웨어"]},
        {n:"EYES Vault",v:"엘에스웨어",l:"Commercial",t:"proprietary",u:"lsware.com",tags:["라이선스","국산"],f:["라이선스 관리","오픈소스 거버넌스","국산 도구"],p:["엘에스웨어"]},
        {n:"FOSSEra",v:"엘에스웨어",l:"Commercial",t:"proprietary",u:"lsware.com",tags:["SCA","라이선스","국산"],f:["오픈소스 검증","라이선스 분석","국산 SCA"],p:["엘에스웨어"]},
        {n:"FOSSGuard",v:"엘에스웨어",l:"Commercial",t:"proprietary",u:"lsware.com",tags:["보안","거버넌스","국산"],f:["오픈소스 보안 관리","취약점 관리","정책 관리"],p:["엘에스웨어"]},
        {n:"FOSSID",v:"FOSSID",l:"Commercial",t:"proprietary",u:"fossid.com",tags:["SCA","라이선스"],f:["오픈소스 식별","코드 스캐닝","라이선스 컴플라이언스"],p:["오에스비씨"]},
        {n:"Snyk",v:"Snyk",l:"Commercial",t:"proprietary",u:"snyk.io",tags:["SCA","보안","DevSecOps"],f:["개발자 중심 보안","의존성 취약점","컨테이너 보안"],p:["오에스비씨"]},
        {n:"Insignary Clarity",v:"인시그너리",l:"Commercial",t:"proprietary",u:"insignary.com",tags:["SCA","바이너리분석","국산"],f:["바이너리 분석","오픈소스 검증","취약점 분석"],p:["오에스비씨"]},
        {n:"Sparrow DAST",v:"스패로우",l:"Commercial",t:"proprietary",u:"sparrowfasoo.com",tags:["DAST","국산","보안"],f:["동적 보안 테스트","웹 취약점","자동 스캔"],p:["스패로우"]},
        {n:"Sparrow SAST",v:"스패로우",l:"Commercial",t:"proprietary",u:"sparrowfasoo.com",tags:["SAST","국산","보안"],f:["정적 코드 분석","소스코드 취약점","다국어 지원"],p:["스패로우"]},
        {n:"Sparrow SCA",v:"스패로우",l:"Commercial",t:"proprietary",u:"sparrowfasoo.com",tags:["SCA","국산","라이선스"],f:["오픈소스 분석","라이선스 검증","취약점 분석"],p:["스패로우"]},
        {n:"FOSSLight Hub",v:"LG전자",l:"Apache 2.0",t:"permissive",u:"fosslight.org",tags:["SCA","라이선스","오픈소스"],f:["오픈소스 관리 플랫폼","라이선스 검증","프로젝트 관리"],p:["LG전자"]},
        {n:"FOSSLight Scanner",v:"LG전자",l:"Apache 2.0",t:"permissive",u:"fosslight.org",tags:["SCA","스캐너","오픈소스"],f:["오픈소스 스캐닝","의존성 분석","라이선스 식별"],p:["LG전자"]},
        {n:"Sonatype Nexus",v:"Sonatype",l:"Commercial",t:"proprietary",u:"sonatype.com",tags:["SCA","레포지토리","보안"],f:["아티팩트 보안","공급망 보안","취약점 관리"],p:["오에스씨코리아","에스코어"]},
        {n:"AUTOCRYPT Security Analyzer",v:"아우토크립트",l:"Commercial",t:"proprietary",u:"autocrypt.co.kr",tags:["보안분석","자동차","국산"],f:["자동차 보안 분석","V2X 보안","IoT 보안"],p:["아우토크립트"]}
    ]
};

// 기술지원 기업 홈페이지 정보 (2025년 KOSSA 솔루션맵 기준)
const providerInfo = {
    "그로윈": {url: "https://www.growin.co.kr", desc: "오픈소스 전문기업"},
    "락플레이스": {url: "https://www.rockplace.com", desc: "오픈소스 기술지원 전문"},
    "에스코어": {url: "https://s-core.co.kr", desc: "삼성그룹 IT 컨설팅"},
    "오픈소스컨설팅": {url: "https://osci.kr", desc: "오픈소스/클라우드 전문"},
    "오에스씨코리아": {url: "https://www.osckorea.com", desc: "클라우드 네이티브 전문"},
    "네오클로바": {url: "http://neoclova.co.kr", desc: "오픈소스 클라우드"},
    "티맥스소프트": {url: "https://www.tmaxsoft.com/kr/main", desc: "국산 SW 전문"},
    "한국레드햇": {url: "https://www.redhat.com/ko", desc: "Red Hat Korea"},
    "아이오차드": {url: "https://iochord.io", desc: "프로세스 분석 솔루션"},
    "와탭랩스": {url: "https://whatap.io", desc: "APM/모니터링"},
    "엑셈": {url: "https://www.ex-em.com", desc: "DB성능관리 전문"},
    "비트나인": {url: "https://bitnine.net", desc: "그래프DB 전문"},
    "큐브리드": {url: "https://www.cubrid.com", desc: "CUBRID DBMS"},
    "알티베이스": {url: "https://www.altibase.com", desc: "하이브리드 DBMS"},
    "선재소프트": {url: "https://www.sunjesoft.com", desc: "인메모리 DB"},
    "인베슘": {url: "https://www.invesume.com", desc: "HamoniKR/교육SW"},
    "한글과컴퓨터": {url: "https://www.hancom.com", desc: "Gooroom/오피스"},
    "티맥스오에스": {url: "https://www.tmaxanc.com", desc: "TmaxOS"},
    "가이아쓰리디": {url: "https://www.gaia3d.com", desc: "3D GIS 전문"},
    "망고시스템": {url: "https://www.mangosystem.com", desc: "GIS 솔루션"},
    "웨이버스": {url: "https://www.waybers.com", desc: "공간정보 전문"},
    "헤르메시스": {url: "https://www.hermesys.co.kr", desc: "GIS/공간분석"},
    "넥스트폼": {url: "https://www.nextfoam.co.kr", desc: "CFD 전문"},
    "지노테크": {url: "https://www.zinotech.co.kr", desc: "Moodle LMS"},
    "오베네프": {url: "https://www.ovenef.com", desc: "Open edX"},
    "엘라스틱서치코리아": {url: "https://www.elastic.co/kr", desc: "Elastic 공식"},
    "서진디에스에이": {url: "https://www.seojindsa.com", desc: "IAM/보안"},
    "스패로우": {url: "https://www.sparrowfasoo.com", desc: "보안취약점 분석"},
    "LG CNS": {url: "https://www.lgcns.com", desc: "IT서비스"},
    "삼성SDS": {url: "https://www.samsungsds.com", desc: "IT서비스"},
    "누리꿈소프트": {url: "https://www.nurisoft.co.kr", desc: "빅데이터/AI"},
    "대보정보통신": {url: "https://www.daebo.com", desc: "IT인프라"},
    "클라우데라": {url: "https://www.cloudera.com", desc: "빅데이터 플랫폼"},
    "솔트룩스": {url: "https://www.saltlux.com", desc: "AI/NLP"},
    "업스테이지": {url: "https://www.upstage.ai", desc: "AI/ML"},
    "카카오브레인": {url: "https://www.kakaobrain.com", desc: "AI 연구"},
    "블로코": {url: "https://www.blocko.io", desc: "블록체인"},
    "아이콘루프": {url: "https://www.iconloop.com", desc: "ICON 블록체인"},
    "엘에스웨어": {url: "https://www.lsware.com", desc: "SW 품질/보안 솔루션"},
    "오에스비씨": {url: "https://www.osbc.co.kr", desc: "오픈소스 컴플라이언스"},
    "진테크이엔지": {url: "https://www.jintech.co.kr", desc: "보안솔루션"},
    "파로스인포": {url: "https://www.parosinfo.com", desc: "IAM 솔루션"},
    "케이티넥스알": {url: "https://www.ktnexr.co.kr", desc: "빅데이터/AI"},
    "맨텍": {url: "https://www.mantech.co.kr", desc: "오픈소스 HA/DR"},
    "유엔진솔루션즈": {url: "https://www.uengine.org", desc: "BPM/클라우드"},
    "핀스정보기술": {url: "https://www.pins.co.kr", desc: "미들웨어/통합"},
    "뉴런시스템": {url: "https://www.neuronsystem.co.kr", desc: "오픈소스 인프라"},
    "지앤클라우드": {url: "https://www.gcloud.co.kr", desc: "검색/클라우드"},
    "리드어스": {url: "https://www.leadus.co.kr", desc: "협업솔루션"},
    "노블시스템": {url: "https://www.noblesystem.co.kr", desc: "ERP/비즈니스"},
    "KIC컨설팅": {url: "https://www.kicco.co.kr", desc: "개발도구"},
    "한국오픈솔루션": {url: "https://www.kosoltech.com", desc: "개발플랫폼"},
    "케이엘정보통신": {url: "https://www.klinfo.co.kr", desc: "시스템통합"},
    "세림티에스지": {url: "https://www.srtsg.co.kr", desc: "오픈소스 인프라"},
    "에스유소프트": {url: "https://www.sulinux.net", desc: "리눅스/서버"},
    "아우토크립트": {url: "https://www.autocrypt.co.kr", desc: "자동차보안"},
    "LG전자": {url: "https://www.lg.co.kr", desc: "FOSSLight 개발"},
    "케이티디에스": {url: "https://www.ktds.com", desc: "IT서비스"},
    "젠탑테크놀로지": {url: "https://www.zentop.co.kr", desc: "IT인프라"},
    "아온소프트": {url: "https://www.aonsoft.co.kr", desc: "오픈소스 전문"},
    "이액티브": {url: "https://www.eactive.co.kr", desc: "IT서비스"}
};

